const ALLOYS = {
  bronze:{name:'Bronze', metals:[['Miedź',88,92,'#d7783e'],['Cyna',8,12,'#b8b3a9']]},
  bismuth:{name:'Bismuth Bronze', metals:[['Miedź',50,65,'#d7783e'],['Cynk',20,30,'#a9a7a0'],['Bizmut',10,20,'#d4a8bd']]},
  black:{name:'Black Bronze', metals:[['Miedź',50,70,'#d7783e'],['Srebro',10,25,'#d7d9da'],['Złoto',10,25,'#e8b53f']]},
  brass:{name:'Brass', metals:[['Miedź',88,92,'#d7783e'],['Cynk',8,12,'#a9a7a0']]},
  rose:{name:'Rose Gold', metals:[['Miedź',15,30,'#d7783e'],['Złoto',70,85,'#e8b53f']]},
  sterling:{name:'Sterling Silver', metals:[['Miedź',20,40,'#d7783e'],['Srebro',60,80,'#d7d9da']]},
  custom:{name:'＋ Dodaj własny stop…', metals:[['Miedź',50,50,'#d7783e'],['Cynk',50,50,'#d7d9da']]}
};
const CUSTOM_ALLOY_COOKIE='tfg_custom_alloys_v2',LEGACY_CUSTOM_COOKIE='tfg_custom_alloy_v1',COOKIE_CONSENT='tfg_cookie_consent_v2',CUSTOM_COLORS=['#9cb76e','#72a9be','#b980cf','#df9b55'];
function getCookie(name){const item=document.cookie.split('; ').find(x=>x.startsWith(`${name}=`));return item?decodeURIComponent(item.slice(name.length+1)):''}
function setCookie(name,value,maxAge=31536000){document.cookie=`${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; SameSite=Lax`}
function deleteCookie(name){document.cookie=`${name}=; Max-Age=0; Path=/; SameSite=Lax`}
let cookieConsent=getCookie(COOKIE_CONSENT),savedCustomAlloys=[];
function sanitizeName(value,fallback){return String(value||'').replace(/[&<>"']/g,'').trim().slice(0,30)||fallback}
function normalizeCustomMetals(metals){if(!Array.isArray(metals)||metals.length<2||metals.length>4)throw Error('Niepoprawne materiały');return metals.map((m,i)=>{const name=sanitizeName(m.name??m[0],`Materiał ${i+1}`),min=Number(m.min??m.percent??m[1]),max=Number(m.max??m[2]??min);if(!Number.isFinite(min)||!Number.isFinite(max)||min<=0||max>100||min>max)throw Error('Niepoprawny zakres udziału');return[name,min,max,CUSTOM_COLORS[i]]})}
function loadCustomAlloyCookie(){if(cookieConsent!=='accepted')return;try{const raw=getCookie(CUSTOM_ALLOY_COOKIE);if(raw){const saved=JSON.parse(raw);if(!Array.isArray(saved))return;savedCustomAlloys=saved.slice(0,5).map((a,i)=>({id:String((Array.isArray(a)?a[0]:a.id)||`alloy-${i+1}`).replace(/[^a-z0-9-]/gi,'').slice(0,40)||`alloy-${i+1}`,name:sanitizeName(Array.isArray(a)?a[1]:a.name,`Własny stop ${i+1}`),metals:normalizeCustomMetals(Array.isArray(a)?a[2]:a.metals)}));return}const legacy=getCookie(LEGACY_CUSTOM_COOKIE);if(legacy){const metals=normalizeCustomMetals(JSON.parse(legacy));savedCustomAlloys=[{id:'alloy-1',name:'Własny stop 1',metals}]}}catch{savedCustomAlloys=[]}}
function saveCustomAlloyCookie(){if(cookieConsent!=='accepted')return;const saved=savedCustomAlloys.map(a=>[a.id,a.name,a.metals.map(m=>[m[0],m[1],m[2]])]);setCookie(CUSTOM_ALLOY_COOKIE,JSON.stringify(saved));deleteCookie(LEGACY_CUSTOM_COOKIE)}
loadCustomAlloyCookie();
const $=s=>document.querySelector(s); let sizes=[144,36]; let lastText='',customSaveTimer=null;
function showCookieNotice(force=false){if(!force&&cookieConsent)return;$('#cookieNotice')?.remove();const notice=document.createElement('aside');notice.id='cookieNotice';notice.className='cookie-notice';notice.setAttribute('role','dialog');notice.setAttribute('aria-label','Ustawienia cookie');notice.innerHTML='<div><b>Zapisywanie własnych stopów</b><p>Strona zapisuje wybór zgody, a po zezwoleniu także nazwy materiałów i procenty własnych stopów. Nie używa analityki ani śledzenia.</p></div><div class="cookie-actions"><button class="cookie-reject" type="button">Nie zapisuj stopów</button><button class="cookie-accept" type="button">Zezwól</button></div>';notice.querySelector('.cookie-accept').onclick=()=>{cookieConsent='accepted';setCookie(COOKIE_CONSENT,cookieConsent);saveCustomAlloyCookie();notice.remove()};notice.querySelector('.cookie-reject').onclick=()=>{cookieConsent='rejected';setCookie(COOKIE_CONSENT,cookieConsent);deleteCookie(CUSTOM_ALLOY_COOKIE);deleteCookie(LEGACY_CUSTOM_COOKIE);notice.remove()};document.body.append(notice)}
function initCookieNotice(){const footer=document.querySelector('footer'),settings=document.createElement('button');settings.type='button';settings.className='cookie-settings';settings.textContent='Ustawienia cookie';settings.onclick=()=>showCookieNotice(true);footer?.append(' · ',settings);showCookieNotice()}
initCookieNotice();
const alloySelect=$('#alloySelect');
function isCustomSelection(){return alloySelect.value==='custom'||alloySelect.value.startsWith('saved:')}
function getCurrentAlloy(){if(alloySelect.value==='custom')return ALLOYS.custom;if(alloySelect.value.startsWith('saved:'))return savedCustomAlloys.find(a=>a.id===alloySelect.value.slice(6))||ALLOYS.custom;return ALLOYS[alloySelect.value]}
function populateAlloySelect(selected='black'){alloySelect.innerHTML='';Object.entries(ALLOYS).filter(([k])=>k!=='custom').forEach(([k,a])=>alloySelect.add(new Option(a.name,k)));savedCustomAlloys.forEach(a=>alloySelect.add(new Option(`★ ${a.name}`,`saved:${a.id}`)));alloySelect.add(new Option(ALLOYS.custom.name,'custom'));alloySelect.value=[...alloySelect.options].some(o=>o.value===selected)?selected:'black'}
populateAlloySelect();

function render(){const a=getCurrentAlloy(),custom=isCustomSelection(),saved=alloySelect.value.startsWith('saved:');$('#customActions').classList.toggle('hidden',!custom);if(custom){$('#customAlloyName').value=a.name==='＋ Dodaj własny stop…'?'':a.name;$('#saveCustomAlloy').textContent=saved?'✓ Zapisz zmiany':'✓ Dodaj stop do listy';$('#deleteCustomAlloy').classList.toggle('hidden',!saved)}$('#recipeInfo').innerHTML=a.metals.map(m=>`<span class="ratio-pill"><b>${m[0]}</b> ${custom?(m[1]===m[2]?m[1]+'%':m[1]+'–'+m[2]+'%'):m[1]+'–'+m[2]+'%'}</span>`).join('');$('#materialRows').innerHTML=a.metals.map((m,i)=>custom?`<div class="material-row custom-metal" data-i="${i}"><div class="custom-editor"><label>Materiał<input class="custom-name" value="${m[0]}" maxlength="30" placeholder="np. Miedź"></label><label>Min %<input class="custom-percent custom-percent-min" type="number" min="0.01" max="100" step="0.01" value="${m[1]}"></label><label>Max %<input class="custom-percent custom-percent-max" type="number" min="0.01" max="100" step="0.01" value="${m[2]}"></label><button class="remove-metal" data-remove="${i}" title="Usuń materiał" ${a.metals.length<=2?'disabled':''}>×</button></div><div class="sizes">${sizes.map((s,j)=>`<div class="unit-input"><input aria-label="${m[0]} porcja ${j+1}" data-size="${j}" type="number" min="0" value="${s}"><span>mB</span></div>`).join('')}</div></div>`:`<div class="material-row" data-i="${i}"><div class="metal-name"><span class="dot" style="color:${m[3]};background:${m[3]}"></span>${m[0]}</div><div class="sizes">${sizes.map((s,j)=>`<div class="unit-input"><input aria-label="${m[0]} porcja ${j+1}" data-size="${j}" type="number" min="0" value="${s}"><span>mB</span></div>`).join('')}</div></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{a.metals.splice(+b.dataset.remove,1);saveCustomAlloyCookie();render()});if(custom)document.querySelectorAll('.custom-name,.custom-percent,#customAlloyName').forEach(x=>x.oninput=queueCustomAlloySave)}

function syncCustom(){if(!isCustomSelection())return;const a=getCurrentAlloy();a.name=sanitizeName($('#customAlloyName').value,'Własny stop');document.querySelectorAll('.material-row').forEach((r,i)=>{const m=a.metals[i],minRaw=r.querySelector('.custom-percent-min').value.trim(),maxRaw=r.querySelector('.custom-percent-max').value.trim(),min=/^\d+(?:\.\d+)?$/.test(minRaw)?Number(minRaw):NaN,max=/^\d+(?:\.\d+)?$/.test(maxRaw)?Number(maxRaw):NaN,name=sanitizeName(r.querySelector('.custom-name').value,`Materiał ${i+1}`);m[0]=name;m[1]=min;m[2]=max});if(alloySelect.value.startsWith('saved:'))alloySelect.selectedOptions[0].textContent=`★ ${a.name}`}
function queueCustomAlloySave(){clearTimeout(customSaveTimer);customSaveTimer=setTimeout(()=>{syncCustom();if(alloySelect.value.startsWith('saved:')&&validateCustomPercentages())saveCustomAlloyCookie()},250)}
function validateCustomPercentages(){const rows=[...document.querySelectorAll('.custom-metal')],status=$('#customPercentStatus');if(!rows.length||!status)return true;let minSum=0,maxSum=0,invalid=false;rows.forEach(row=>{const minInput=row.querySelector('.custom-percent-min'),maxInput=row.querySelector('.custom-percent-max'),minRaw=minInput.value.trim(),maxRaw=maxInput.value.trim(),min=Number(minRaw),max=Number(maxRaw),numbersValid=/^\d+(?:\.\d+)?$/.test(minRaw)&&/^\d+(?:\.\d+)?$/.test(maxRaw)&&Number.isFinite(min)&&Number.isFinite(max)&&min>0&&max<=100,pairValid=numbersValid&&min<=max;minInput.classList.toggle('invalid',!pairValid);maxInput.classList.toggle('invalid',!pairValid);if(pairValid){minSum+=min;maxSum+=max}else invalid=true});status.className='custom-percent-status';if(invalid){status.classList.add('bad');status.textContent='Niepoprawny zakres — Min i Max muszą być liczbami od 0 do 100, a Min nie może przekraczać Max.';return false}if(minSum>100.000001){status.classList.add('bad');status.textContent=`Suma minimów: ${minSum.toFixed(2)}% — przekroczono 100%.`;return false}if(maxSum<99.999999){status.classList.add('bad');status.textContent=`Suma maksimów: ${maxSum.toFixed(2)}% — nie można osiągnąć 100%.`;return false}status.classList.add('ok');status.textContent=`Zakresy pozwalają uzyskać 100% ✓ (min. ${minSum.toFixed(2)}%, maks. ${maxSum.toFixed(2)}%)`;return true}
document.addEventListener('beforeinput',e=>{if(e.target.matches?.('.custom-percent')&&e.data&&/[^0-9.]/.test(e.data))e.preventDefault()});document.addEventListener('keydown',e=>{if(e.target.matches?.('.custom-percent')&&['e','E','+','-'].includes(e.key))e.preventDefault()});document.addEventListener('input',e=>{if(e.target.matches?.('.custom-percent'))validateCustomPercentages()});

function solve(){syncCustom();const a=getCurrentAlloy(),cap=+$('#capacity').value||3024,target=$('#fillMax').checked?cap:Math.min(cap,+$('#target').value||cap);if(a.metals.some(m=>!Number.isFinite(m[1])||!Number.isFinite(m[2])||m[1]<=0||m[2]>100||m[1]>m[2]))return showError('Każdy udział procentowy musi być większy od 0 i nie może przekraczać 100%.');const minSum=a.metals.reduce((n,m)=>n+m[1],0),maxSum=a.metals.reduce((n,m)=>n+m[2],0);if(minSum>100||maxSum<100)return showError(`Z tych zakresów nie da się złożyć 100% stopu. Suma minimów: ${minSum}%, suma maksimów: ${maxSum}%.`);const rows=[...document.querySelectorAll('.material-row')];const units=rows.map(r=>[...r.querySelectorAll('.sizes input')].map(x=>+x.value).filter(x=>x>0));if(units.some(x=>!x.length))return showError('Każdy metal musi mieć przynajmniej jedną porcję większą od 0.');
  const tables=units.map(us=>{
    const dp=Array(target+1).fill(null);dp[0]={count:0,counts:Array(us.length).fill(0)};
    for(let mb=1;mb<=target;mb++)for(let j=0;j<us.length;j++){
      const u=us[j],prev=dp[mb-u];if(!prev)continue;
      if(!dp[mb]||prev.count+1<dp[mb].count){const counts=prev.counts.slice();counts[j]++;dp[mb]={count:prev.count+1,counts}}
    }
    const list=[];for(let mb=1;mb<=target;mb++)if(dp[mb])list.push({mb,count:dp[mb].count,parts:dp[mb].counts.map((n,j)=>({u:us[j],n})).filter(p=>p.n).sort((x,y)=>y.u-x.u)});
    return {list,byMb:new Map(list.map(o=>[o.mb,o]))};
  });
  let best=null;
  const better=c=>{const score=[-c.sum,c.count];c.score=score;if(!best||score[0]<best.score[0]||(score[0]===best.score[0]&&score[1]<best.score[1]))best=c};
  const findAtTotal=total=>{
    const lists=tables.map((t,i)=>t.list.filter(o=>{const pct=o.mb/total*100;return pct>=a.metals[i][1]-1e-9&&pct<=a.metals[i][2]+1e-9}));
    if(lists.some(x=>!x.length))return false;let found=false;
    const walk=(idx,chosen,sum,count)=>{
      if(idx===tables.length-1){const last=tables[idx].byMb.get(total-sum);if(!last)return;const pct=last.mb/total*100;if(pct<a.metals[idx][1]-1e-9||pct>a.metals[idx][2]+1e-9)return;found=true;better({chosen:[...chosen,last],sum:total,count:count+last.count});return}
      const remaining=total-sum;for(const o of lists[idx]){if(o.mb>=remaining)break;walk(idx+1,[...chosen,o],sum+o.mb,count+o.count)}
    };walk(0,[],0,0);return found;
  };
  for(let total=target;total>0;total--)if(findAtTotal(total))break;
  if(!best)return showError('Nie ma poprawnej kombinacji dla tych rozmiarów porcji i pojemności. Dodaj mniejszą porcję (np. 16 lub 36 mB).');show(best,a,cap)}

function show(b,a,cap){$('#results').classList.remove('hidden');$('#statusBadge').className='badge';$('#statusBadge').textContent='POPRAWNY STOP';$('#resultCards').innerHTML=b.chosen.map((x,i)=>{const pct=(x.mb/b.sum*100).toFixed(2);const detail=x.parts.map(p=>`${p.n} × ${p.u} mB`).join(' + ');return `<div class="result-card"><div><h3>${a.metals[i][0]}</h3><p>${detail} · ${x.mb} mB · ${pct}% (wymagane ${a.metals[i][1]}–${a.metals[i][2]}%)</p></div><div class="count">${x.count}<small>PORCJI</small></div></div>`}).join('');const fill=b.sum/cap*100;$('#fillBar').style.width=Math.min(100,fill)+'%';$('#totalMb').textContent=b.sum;$('#capacityOut').textContent=cap;$('#fillPercent').textContent=fill.toFixed(1)+'%';$('#itemCount').textContent=b.count;$('#ingotCount').textContent=Math.floor(b.sum/144);$('#remainder').textContent=(b.sum%144)+' mB';lastText=`${a.name} — ${b.sum} mB\n`+b.chosen.map((x,i)=>`${a.metals[i][0]}: ${x.parts.map(p=>`${p.n} × ${p.u} mB`).join(' + ')} = ${x.mb} mB (${(x.mb/b.sum*100).toFixed(2)}%)`).join('\n');$('#solverNote').textContent='Solver sprawdził całkowite kombinacje porcji i wybrał poprawny stop możliwie najbliżej podanej wartości mB.';$('#results').scrollIntoView({behavior:'smooth',block:'start'})}
function showError(msg){$('#results').classList.remove('hidden');$('#statusBadge').className='badge bad';$('#statusBadge').textContent='BRAK KOMBINACJI';$('#resultCards').innerHTML=`<div class="result-card"><div><h3>Nie udało się ułożyć stopu</h3><p>${msg}</p></div></div>`;$('#solverNote').textContent='Zmień wielkości porcji lub pojemność i spróbuj ponownie.'}
alloySelect.onchange=()=>{clearTimeout(customSaveTimer);render()};
$('#addSize').onclick=()=>{syncCustom();sizes.push(16);render()};
$('#addMetal').onclick=()=>{syncCustom();const a=getCurrentAlloy();if(a.metals.length>=4)return showError('Waza ma 4 sloty, dlatego własny stop może zawierać maksymalnie 4 materiały.');const i=a.metals.length;a.metals.push([`Materiał ${i+1}`,0,0,CUSTOM_COLORS[i]]);saveCustomAlloyCookie();render()};
$('#saveCustomAlloy').onclick=()=>{syncCustom();const a=getCurrentAlloy(),minSum=a.metals.reduce((n,m)=>n+m[1],0),maxSum=a.metals.reduce((n,m)=>n+m[2],0);if(a.metals.some(m=>!Number.isFinite(m[1])||!Number.isFinite(m[2])||m[1]<=0||m[2]>100||m[1]>m[2])||minSum>100.0001||maxSum<99.9999)return showError('Sprawdź zakresy procentowe — muszą pozwalać na uzyskanie łącznie 100%.');if(alloySelect.value==='custom'){if(savedCustomAlloys.length>=5)return showError('Możesz zapisać maksymalnie 5 własnych stopów w cookie.');const id=`alloy-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,entry={id,name:a.name,metals:a.metals.map(m=>[...m])};savedCustomAlloys.push(entry);ALLOYS.custom={name:'＋ Dodaj własny stop…',metals:[['Miedź',50,50,CUSTOM_COLORS[0]],['Cynk',50,50,CUSTOM_COLORS[1]]]};populateAlloySelect(`saved:${id}`)}saveCustomAlloyCookie();render();if(cookieConsent!=='accepted')showCookieNotice(true)};
$('#deleteCustomAlloy').onclick=()=>{if(!alloySelect.value.startsWith('saved:'))return;const a=getCurrentAlloy();if(!confirm(`Usunąć zapisany stop „${a.name}”?`))return;savedCustomAlloys=savedCustomAlloys.filter(x=>x.id!==a.id);saveCustomAlloyCookie();populateAlloySelect('black');render()};
$('#calculateBtn').onclick=solve;$('#resetBtn').onclick=()=>{sizes=[144,36];ALLOYS.custom={name:'＋ Dodaj własny stop…',metals:[['Miedź',50,50,CUSTOM_COLORS[0]],['Cynk',50,50,CUSTOM_COLORS[1]]]};populateAlloySelect('black');$('#capacity').value=$('#target').value=3024;$('#fillMax').checked=true;$('#target').disabled=true;$('#bloomCapacity').value=112;$('#bloomAvailable').value=0;$('#bloomMbItem').value=129;$('#bloomMbPer').value=100;$('#bloomCoalPer').value=2;$('#anvilStart').value=0;$('#anvilTarget').value=80;document.querySelectorAll('.anvil-rule').forEach(x=>x.value='');document.querySelectorAll('.anvil-constraint').forEach(x=>x.value='any');render();document.querySelectorAll('.results').forEach(x=>x.classList.add('hidden'))};$('#capacity').oninput=e=>{if($('#fillMax').checked)$('#target').value=e.target.value};$('#fillMax').onchange=e=>{if(e.target.checked)$('#target').value=$('#capacity').value;$('#target').disabled=e.target.checked};$('#target').disabled=true;$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(lastText);$('#copyBtn').textContent='Skopiowano ✓';setTimeout(()=>$('#copyBtn').textContent='Kopiuj rozpiskę',1400)};render();
new MutationObserver(()=>{if(isCustomSelection())validateCustomPercentages()}).observe($('#materialRows'),{childList:true});

const TOOL_COPY={alloy:['TFG TOOLKIT','Kalkulator stopów','Oblicza proporcje i liczbę porcji metali dla wybranej pojemności.'],bloomery:['TFG TOOLKIT','Kalkulator Bloomery','Oblicza ilość materiału, charcoal oraz liczbę otrzymanych bloomów.'],anvil:['TFG TOOLKIT','Solver kowadła','Odczytuje GUI kowadła i na bieżąco pokazuje kolejne operacje.']};
function activateTool(name){if(!TOOL_COPY[name])name='alloy';document.querySelectorAll('.tool-tab,.tool-view').forEach(x=>x.classList.remove('active'));document.querySelector(`.tool-tab[data-tool="${name}"]`).classList.add('active');$(`#${name}Tool`).classList.add('active');const c=TOOL_COPY[name];$('.hero .eyebrow').textContent=c[0];$('.hero h1').innerHTML=c[1];$('.hero .lede').textContent=c[2]}
activateTool(document.body.dataset.tool);

function calculateBloomery(){const cap=Math.floor(+$(`#bloomCapacity`).value),available=Math.floor(+$(`#bloomAvailable`).value),mbItem=+$(`#bloomMbItem`).value,mbPer=+$(`#bloomMbPer`).value,coalPer=+$(`#bloomCoalPer`).value,whole=$('#bloomWhole').checked;if(![cap,mbItem,mbPer].every(x=>Number.isFinite(x)&&x>0)||!Number.isFinite(coalPer)||coalPer<0)return alert('Sprawdź wartości Bloomery.');let best=null,maxMetal=Math.min(cap,available>0?available:cap);for(let metal=1;metal<=maxMetal;metal++){const blooms=Math.floor(metal*mbItem/mbPer+1e-9),coal=Math.ceil(blooms*coalPer-1e-9),slots=metal+coal;if(!blooms||slots>cap)continue;const waste=metal*mbItem-blooms*mbPer;if(!best||blooms>best.blooms||(blooms===best.blooms&&((whole&&metal<best.metal)||(!whole&&metal>best.metal))))best={metal,blooms,coal,slots,waste,total:metal*mbItem}}if(!best){$('#bloomResults').classList.remove('hidden');$('#bloomCards').innerHTML='<div class="metric-card"><span>Brak wyniku</span><b>—</b><small>Zwiększ pojemność lub ilość materiału.</small></div>';return}$('#bloomResults').classList.remove('hidden');$('#bloomCards').innerHTML=`<div class="metric-card"><span>Pył / materiał</span><b>${best.metal}</b><small>${best.total} mB żelaza</small></div><div class="metric-card"><span>Charcoal</span><b>${best.coal}</b><small>${coalPer} na bloom</small></div><div class="metric-card"><span>Raw Iron Blooms</span><b>${best.blooms}</b><small>${best.blooms*mbPer} mB wykorzystane</small></div><div class="metric-card"><span>Zajęte miejsca</span><b>${best.slots}/${cap}</b><small>${cap-best.slots} wolnych</small></div>`;$('#bloomNote').textContent=`Reszta żelaza: ${best.waste.toFixed(0)} mB. Wsad: ${best.metal} × materiał po ${mbItem} mB + ${best.coal} × charcoal.`;$('#bloomResults').scrollIntoView({behavior:'smooth',block:'start'})}
$('#bloomCalculate').onclick=calculateBloomery;

let anvilImageReady=false,anvilGuiCache=null,anvilCaptureStream=null,anvilCaptureVideo=null,anvilCaptureTimer=null,anvilLastLocate=0,anvilLastAnalyze=0,anvilLastRules=0,anvilRulesCache=[],anvilMarkerState={accepted:null,pending:null,count:0};
function setCaptureStatus(message,type=''){$('#captureStatus').textContent=message;$('#captureStatus').className=`capture-status ${type}`}
function resetAnvilMarkerState(){anvilMarkerState={accepted:null,pending:null,count:0};if(anvilCaptureStream)$('#anvilResults')?.classList.add('hidden')}
function drawAnvilImage(source,silent=false){const canvas=$('#anvilCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),w=source.naturalWidth||source.videoWidth||source.width,h=source.naturalHeight||source.videoHeight||source.height;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;anvilGuiCache=null;anvilRulesCache=[];anvilLastRules=0;resetAnvilMarkerState()}ctx.imageSmoothingEnabled=false;ctx.drawImage(source,0,0,w,h);$('#captureDrop').classList.add('has-image');$('#analyzeAnvil').disabled=false;anvilImageReady=true;if(!silent)setCaptureStatus(`Wczytano obraz ${w} × ${h}. Kliknij „Odczytaj wartości”.`,'ok')}
function stopAnvilCapture(message='Przechwytywanie zatrzymane — pozostawiono ostatnią klatkę.'){if(anvilCaptureTimer){clearInterval(anvilCaptureTimer);anvilCaptureTimer=null}anvilCaptureStream?.getTracks().forEach(t=>t.stop());if(anvilCaptureVideo)anvilCaptureVideo.srcObject=null;anvilCaptureStream=anvilCaptureVideo=null;liveAnvilState=null;resetAnvilMarkerState();document.body.classList.remove('anvil-live');$('#anvilTool').classList.remove('live-mode');$('#anvilTool .workspace').classList.remove('hidden');$('#captureScreen').textContent='▣ Uruchom podgląd Minecrafta';if(message)setCaptureStatus(message,'ok')}
function loadAnvilFile(file){if(anvilCaptureStream)stopAnvilCapture('');document.body.classList.remove('anvil-live');$('#anvilTool').classList.remove('live-mode');$('#anvilTool').classList.add('static-image-mode');$('#anvilTool .workspace').classList.remove('hidden');if(!file||!file.type.startsWith('image/'))return setCaptureStatus('Ten plik nie jest obsługiwanym obrazem.','bad');const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{anvilGuiCache=null;anvilRulesCache=[];anvilLastRules=0;resetAnvilMarkerState();drawAnvilImage(img,true);analyzeAnvilImage(false);refreshRulePreviews();if(anvilMarkerState.accepted){calculateAnvil(false);setCaptureStatus(`${$('#captureStatus').textContent} Tryb statyczny — obraz nie jest dalej aktualizowany.`,'ok')}URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);setCaptureStatus('Nie udało się otworzyć obrazu.','bad')};img.src=url}
$('#uploadAnvil').onclick=()=>$('#anvilFile').click();$('#anvilFile').onchange=e=>loadAnvilFile(e.target.files[0]);
$('#captureScreen').onclick=async()=>{if(anvilCaptureStream)return stopAnvilCapture();if(!navigator.mediaDevices?.getDisplayMedia)return setCaptureStatus('Ta przeglądarka nie obsługuje przechwytywania ekranu. Użyj wczytania screena.','bad');try{anvilCaptureStream=await navigator.mediaDevices.getDisplayMedia({video:{cursor:'never',frameRate:{ideal:30,max:60}},audio:false});anvilCaptureVideo=document.createElement('video');anvilCaptureVideo.srcObject=anvilCaptureStream;anvilCaptureVideo.muted=true;anvilCaptureVideo.playsInline=true;await anvilCaptureVideo.play();anvilGuiCache=null;anvilRulesCache=[];liveAnvilState=null;resetAnvilMarkerState();anvilLastLocate=anvilLastAnalyze=anvilLastRules=0;document.body.classList.add('anvil-live');$('#anvilTool').classList.remove('static-image-mode');$('#anvilTool').classList.add('live-mode');$('#anvilTool .workspace').classList.add('hidden');$('#captureScreen').textContent='■ Zatrzymaj podgląd';setCaptureStatus('Podgląd aktywny — sekwencja jest wyświetlana obok przechwytywanego obrazu.','ok');const update=()=>{if(!anvilCaptureVideo||anvilCaptureVideo.readyState<2)return;drawAnvilImage(anvilCaptureVideo,true);const now=performance.now();if(now-anvilLastAnalyze>=100){anvilLastAnalyze=now;analyzeAnvilImage(true)}};anvilCaptureStream.getVideoTracks()[0].addEventListener('ended',()=>stopAnvilCapture());update();anvilCaptureTimer=setInterval(update,33)}catch(e){stopAnvilCapture('');if(e.name!=='NotAllowedError')setCaptureStatus(`Nie udało się przechwycić ekranu: ${e.message}`,'bad');else setCaptureStatus('Przechwytywanie anulowane.','bad')}};
const drop=$('#captureDrop');drop.ondragover=e=>{e.preventDefault();drop.style.borderColor='var(--orange)'};drop.ondragleave=()=>drop.style.borderColor='';drop.ondrop=e=>{e.preventDefault();drop.style.borderColor='';loadAnvilFile(e.dataTransfer.files[0])};document.addEventListener('paste',e=>{const file=[...e.clipboardData.items].find(x=>x.type.startsWith('image/'))?.getAsFile();if(file){activateTool('anvil');loadAnvilFile(file)}});
function median(values){const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function locateAnvilGui(source){const w=source.width,h=source.height,ctx=source.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,w,h).data,mask=new Uint8Array(w*h),seen=new Uint8Array(w*h),queue=new Int32Array(w*h);for(let i=0;i<w*h;i++){const r=data[i*4],g=data[i*4+1],b=data[i*4+2];if(r>=185&&r<=210&&Math.abs(r-g)<=3&&Math.abs(g-b)<=3)mask[i]=1}let best=null;for(let start=0;start<mask.length;start++){if(!mask[start]||seen[start])continue;let head=0,tail=0;queue[tail++]=start;seen[start]=1;let count=0,minX=w,maxX=0,minY=h,maxY=0;while(head<tail){const p=queue[head++],x=p%w,y=(p/w)|0;count++;if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;const add=n=>{if(n>=0&&n<mask.length&&mask[n]&&!seen[n]){seen[n]=1;queue[tail++]=n}};if(x>0)add(p-1);if(x<w-1)add(p+1);if(y>0)add(p-w);if(y<h-1)add(p+w)}const cw=maxX-minX+1,ch=maxY-minY+1,ratio=cw/ch;if(count>1000&&ratio>.72&&ratio<.98&&(!best||count>best.count))best={count,minX,maxX,minY,maxY,cw,ch}}if(!best)return null;const scale=Math.max(1,Math.round(best.cw/170)),pad=2*scale,x=Math.max(0,best.minX-pad),y=Math.max(0,best.minY-pad),right=Math.min(w,best.maxX+pad+1),bottom=Math.min(h,best.maxY+pad+1);return{x,y,w:right-x,h:bottom-y,minX:best.minX,minY:best.minY,maxX:best.maxX,maxY:best.maxY,scale}}
function findAnvilMarker(data,width,height,x0,y0,s,test,yMin,yMax){const mask=new Uint8Array(width*height),seen=new Uint8Array(width*height),queue=new Int32Array(width*height);for(let y=0;y<height;y++){const ay=y+y0;if(ay<yMin||ay>yMax)continue;for(let x=0;x<width;x++){const i=(y*width+x)*4;if(test(data[i],data[i+1],data[i+2]))mask[y*width+x]=1}}let best=null;for(let start=0;start<mask.length;start++){if(!mask[start]||seen[start])continue;let head=0,tail=0,count=0,minX=width,maxX=0,minY=height,maxY=0;queue[tail++]=start;seen[start]=1;while(head<tail){const p=queue[head++],x=p%width,y=(p/width)|0;count++;if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){if(!ox&&!oy)continue;const nx=x+ox,ny=y+oy;if(nx<0||nx>=width||ny<0||ny>=height)continue;const n=ny*width+nx;if(mask[n]&&!seen[n]){seen[n]=1;queue[tail++]=n}}}const w=maxX-minX+1,h=maxY-minY+1;if(w<2*s||w>4*s||h<s||h>3*s||count<Math.max(2,1.5*s*s)||count>7*s*s)continue;const score=Math.abs(w-3*s)+Math.abs(h-2*s)+Math.abs(count-3*s*s)/Math.max(1,s);if(!best||score<best.score)best={x:minX+x0,score}}return best?.x??null}
function readAnvilMarkers(source,gui){const ctx=source.getContext('2d',{willReadFrequently:true}),s=gui.scale,x0=Math.max(0,gui.minX+8*s),x1=Math.min(source.width-1,gui.minX+164*s),y0=Math.max(0,Math.round(gui.minY+90*s)),y1=Math.min(source.height-1,Math.round(gui.minY+103*s)),width=x1-x0+1,height=y1-y0+1;if(width<=0||height<=0)return null;const data=ctx.getImageData(x0,y0,width,height).data,redX=findAnvilMarker(data,width,height,x0,y0,s,(r,g,b)=>r>220&&g<55&&b<55,y0,gui.minY+97*s),greenX=findAnvilMarker(data,width,height,x0,y0,s,(r,g,b)=>g>190&&r<65&&b<90,gui.minY+96*s,y1);if(redX===null||greenX===null)return null;const zeroX=gui.minX+11*s,target=Math.round((redX-zeroX)/s),current=Math.round((greenX-zeroX)/s);return{target:Math.max(0,Math.min(150,target)),current:Math.max(0,Math.min(150,current))}}
function stabilizeAnvilMarkers(values,live){if(!live){anvilMarkerState={accepted:values,pending:null,count:0};return values}if(!values)return anvilMarkerState.accepted;const key=`${values.current}|${values.target}`,accepted=anvilMarkerState.accepted;if(accepted&&accepted.current===values.current&&accepted.target===values.target){anvilMarkerState.pending=null;anvilMarkerState.count=0;return accepted}if(anvilMarkerState.pending?.key===key)anvilMarkerState.count++;else{anvilMarkerState.pending={key,values};anvilMarkerState.count=1}if(anvilMarkerState.count<3)return accepted;anvilMarkerState={accepted:values,pending:null,count:0};return values}
const ANVIL_RULE_TEMPLATES={punch:[0,0,0,0,0,0,231416,231416,249848,262128,262112,0,0,0,14,193,486,200,200,15],bend:[0,0,0,0,0,32752,65520,65520,65504,62400,61440,63488,61440,61440,49167,193,486,198,198,6],upset:[0,0,0,0,245760,261120,262136,262136,262136,262136,262128,260096,229376,229376,207,2497,15566,2241,2241,495],shrink:[0,0,196608,196608,229376,245760,262136,262136,65528,65520,2016,0,0,0,199,2504,15567,2249,2249,495],light:[0,0,258048,258048,258048,258048,260088,260088,258048,258048,245760,0,0,0,15,28673,29166,1,1,15],medium:[0,0,258048,258048,258048,258048,260088,260088,258048,258048,245760,448,448,448,7,28680,29167,9,9,15],hard:[0,0,258048,258048,258048,258048,260088,260088,258048,258048,245760,448,448,448,15,243721,244207,1,1,14],draw:[0,0,0,0,0,56,248,248,1016,262128,262112,0,0,0,207,456,15567,193,193,494]};
const anvilRuleMaskCache=new Map();
const ANVIL_ICON_LABELS={hit:'Hit',light:'Light Hit',medium:'Medium Hit',hard:'Hard Hit',draw:'Draw',punch:'Punch',bend:'Bend',upset:'Upset',shrink:'Shrink'};
function actionIcon(id,large=false){const key=id==='hit'?'light':id,rows=ANVIL_RULE_TEMPLATES[key];if(!rows)return'';let path='';const maxY=id==='hit'?14:20;for(let y=0;y<maxY;y++){let x=0;while(x<20){while(x<20&&!(rows[y]&(1<<(19-x))))x++;const start=x;while(x<20&&rows[y]&(1<<(19-x)))x++;if(x>start)path+=`M${start} ${y}h${x-start}v1H${start}z`}}return `<svg class="anvil-action-icon${large?' large':''}" viewBox="0 0 20 20" shape-rendering="crispEdges" role="img" aria-label="${ANVIL_ICON_LABELS[id]||id}"><path fill="currentColor" d="${path}"/></svg>`}
function getAnvilRuleMasks(size){if(anvilRuleMaskCache.has(size))return anvilRuleMaskCache.get(size);const masks={};for(const[name,rows]of Object.entries(ANVIL_RULE_TEMPLATES)){const mask=new Uint8Array(size*size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const sy=Math.min(19,Math.floor(y*20/size)),sx=Math.min(19,Math.floor(x*20/size));if(rows[sy]&(1<<(19-sx)))mask[y*size+x]=1}masks[name]=mask}anvilRuleMaskCache.set(size,masks);return masks}
function readAnvilRuleConstraint(ctx,gui,slot){const s=gui.scale,x0=Math.round(gui.x+(57+20*slot)*s),x1=Math.round(gui.x+(73+20*slot)*s),width=Math.max(1,x1-x0),active=[26,24,22].map(offset=>{const y=Math.round(gui.y+offset*s+Math.floor(s/2)),data=ctx.getImageData(x0,y,width,Math.max(1,s)).data;let colored=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];if(r>90&&r>g*1.25&&b<100||g>60&&g>r*1.25&&b<110)colored++}return colored>data.length/4*.35});const[last,second,third]=active;if(last&&second&&third)return'any';if(!last&&second&&third)return'notlast';if(last&&!second&&!third)return'last';if(!last&&second&&!third)return'second';if(!last&&!second&&third)return'third';return'unknown'}
function readAnvilRules(source,gui){const ctx=source.getContext('2d',{willReadFrequently:true}),s=gui.scale,slotSize=20*s,templateSize=10*s,masks=getAnvilRuleMasks(templateSize),rules=[];for(let slot=0;slot<3;slot++){const left=Math.round(gui.minX+(54+20*slot)*s),top=Math.round(gui.minY+5*s),box=ctx.getImageData(left,top,slotSize,slotSize).data,actual=new Uint8Array(slotSize*slotSize);let colored=0;for(let p=0;p<actual.length;p++){const i=p*4,r=box[i],g=box[i+1],b=box[i+2];if(r>100&&r>g*1.5&&b<90||g>65&&g>r*1.4&&b<100)colored++;if(Math.min(r,g,b)>130&&Math.max(r,g,b)-Math.min(r,g,b)<35)actual[p]=1}if(colored<=4*s*s){rules.push({action:'',constraint:'any'});continue}let bestName='hit',bestScore=0;const expectedX=Math.round(6.5*s),expectedY=2*s,radius=2*s;for(const[name,mask]of Object.entries(masks))for(let oy=Math.max(0,expectedY-radius);oy<=Math.min(slotSize-templateSize,expectedY+radius);oy++)for(let ox=Math.max(0,expectedX-radius);ox<=Math.min(slotSize-templateSize,expectedX+radius);ox++){let intersection=0,union=0;for(let y=0;y<templateSize;y++)for(let x=0;x<templateSize;x++){const a=actual[(oy+y)*slotSize+ox+x],e=mask[y*templateSize+x];if(a||e)union++;if(a&&e)intersection++}const score=union?intersection/union:0;if(score>bestScore){bestScore=score;bestName=name}}if(bestScore<.62||bestName==='light'||bestName==='medium'||bestName==='hard')bestName='hit';rules.push({action:bestName,constraint:readAnvilRuleConstraint(ctx,gui,slot)})}return rules}
function analyzeAnvilImage(live=false){if(!anvilImageReady)return;const source=$('#anvilCanvas'),normalized=document.createElement('canvas');normalized.width=344;normalized.height=407;const ctx=normalized.getContext('2d',{willReadFrequently:true}),ratio=source.width/source.height,expected=344/407;let gui=anvilGuiCache,values=gui&&readAnvilMarkers(source,gui);if(!values&&(!live||Date.now()-anvilLastLocate>1500)){anvilLastLocate=Date.now();gui=locateAnvilGui(source);anvilGuiCache=gui;values=gui&&readAnvilMarkers(source,gui)}let crop={x:0,y:0,w:source.width,h:source.height},autoCropped=false;if(Math.abs(ratio-expected)>.06){if(!gui){if(!live)setCaptureStatus('Nie udało się odnaleźć panelu kowadła w przechwyconym oknie. Spróbuj wczytać przycięty screenshot.','bad');return}crop=gui;autoCropped=true}ctx.imageSmoothingEnabled=false;ctx.drawImage(source,crop.x,crop.y,crop.w,crop.h,0,0,344,407);const pixels=ctx.getImageData(0,0,344,407).data,pixel=(x,y)=>{const i=(y*344+x)*4;return[pixels[i],pixels[i+1],pixels[i+2]]};if(!values&&!gui){const redX=[],greenX=[];for(let y=180;y<198;y++)for(let x=20;x<327;x++){const[r,g,b]=pixel(x,y);if(r>50&&r>g*1.35&&r>b*1.25)redX.push(x)}for(let y=198;y<206;y++)for(let x=20;x<327;x++){const[r,g,b]=pixel(x,y);if(g>45&&g>r*1.25&&g>b*1.1)greenX.push(x)}if(redX.length<6||greenX.length<4){if(!live)setCaptureStatus('Panel został znaleziony, ale nie widzę obu markerów. Upewnij się, że wybrano plan.','bad');return}values={target:Math.max(0,Math.min(150,Math.round((median(redX)-27.5)/2))),current:Math.max(0,Math.min(150,Math.round((median(greenX)-27.5)/2)))}}values=stabilizeAnvilMarkers(values,live);if(!values){if(!live)setCaptureStatus('Panel został znaleziony, ale nie widzę obu markerów. Upewnij się, że wybrano plan.','bad');return}const{target,current}=values;$('#anvilStart').value=current;$('#anvilTarget').value=target;if(gui&&(!live||Date.now()-anvilLastRules>=750)){anvilLastRules=Date.now();anvilRulesCache=readAnvilRules(source,gui);const fields=[['#ruleLast','#ruleLastConstraint'],['#ruleSecond','#ruleSecondConstraint'],['#ruleThird','#ruleThirdConstraint']];fields.forEach(([actionId,constraintId],i)=>{const rule=anvilRulesCache[i]||{};$(actionId).value=rule.action||'';$(constraintId).value=rule.constraint||'any'})}const ruleLabels={hit:'Hit',draw:'Draw',punch:'Punch',bend:'Bend',upset:'Upset',shrink:'Shrink'},constraintLabels={unknown:'nie odczytano',last:'ostatnia',second:'2. od końca',third:'3. od końca',notlast:'nie ostatnia',any:'dowolna z ostatnich 3'},details=anvilRulesCache.map(rule=>rule?.action?`${ruleLabels[rule.action]} (${constraintLabels[rule.constraint]||rule.constraint})`:'').filter(Boolean),activeRules=details.length;setCaptureStatus(`${live?'Podgląd aktywny. ':autoCropped?'Automatycznie znaleziono panel. ':''}Odczytano: aktualna wartość ${current}, cel ${target}.${activeRules?` Zasady: ${details.join(', ')}.`:' Nie wykryto aktywnych zasad.'}`,'ok')}
$('#analyzeAnvil').onclick=()=>{resetAnvilMarkerState();analyzeAnvilImage(false);refreshRulePreviews();if(anvilMarkerState.accepted)calculateAnvil(false)};

const ANVIL_ACTIONS=[{id:'light',name:'Light Hit',d:-3},{id:'medium',name:'Medium Hit',d:-6},{id:'hard',name:'Hard Hit',d:-9},{id:'draw',name:'Draw',d:-15},{id:'punch',name:'Punch',d:2},{id:'bend',name:'Bend',d:7},{id:'upset',name:'Upset',d:13},{id:'shrink',name:'Shrink',d:16}],ANVIL_FAMILIES={hit:['light','medium','hard'],draw:['draw'],punch:['punch'],bend:['bend'],upset:['upset'],shrink:['shrink']};
const ANVIL_CONSTRAINT_LABELS={unknown:'Nie odczytano — wybierz ręcznie',any:'Dowolna z ostatnich 3',notlast:'Nie ostatnia',last:'Ostatnia',second:'2. od końca',third:'3. od końca'},ruleOptions=[['','Brak'],['hit','Hit'],['draw','Draw'],['punch','Punch'],['bend','Bend'],['upset','Upset'],['shrink','Shrink']],constraintOptions=Object.entries(ANVIL_CONSTRAINT_LABELS);document.querySelectorAll('.anvil-rule').forEach(s=>{ruleOptions.forEach(([v,n])=>s.add(new Option(n,v)));s.onchange=refreshRulePreviews});document.querySelectorAll('.anvil-constraint').forEach(s=>{constraintOptions.forEach(([v,n])=>s.add(new Option(n,v)));s.onchange=refreshRulePreviews});
function refreshRulePreviews(){document.querySelectorAll('.anvil-rule').forEach(s=>{const label=s.closest('label'),constraint=label.querySelector('.anvil-constraint'),preview=label.querySelector('.rule-preview'),key=`${s.value}|${constraint.value}`;constraint.disabled=!s.value;if(!preview||preview.dataset.rule===key)return;preview.dataset.rule=key;preview.innerHTML=s.value?`${actionIcon(s.value)}<span>${ANVIL_ICON_LABELS[s.value]} · ${ANVIL_CONSTRAINT_LABELS[constraint.value]}</span>`:''})}
refreshRulePreviews();$('#resetBtn').addEventListener('click',()=>setTimeout(refreshRulePreviews));
function anvilBfs(start,goal){if(start===goal)return[];const queue=[start],seen=Array(151).fill(false),prev=Array(151);seen[start]=true;for(let q=0;q<queue.length;q++){const pos=queue[q];for(const action of ANVIL_ACTIONS){const next=pos+action.d;if(next<0||next>150||seen[next])continue;seen[next]=true;prev[next]=[pos,action];if(next===goal){const path=[];for(let x=goal;x!==start;){const [p,a]=prev[x];path.push(a);x=p}return path.reverse()}queue.push(next)}}return null}
function anvilActionMatches(actionId,ruleAction){return ruleAction==='hit'?['light','medium','hard'].includes(actionId):actionId===ruleAction}
function anvilRulesSatisfied(tail,rules){if(!rules.length)return true;const rank={last:0,second:0,third:0,notlast:1,any:2},ordered=[...rules].sort((a,b)=>(rank[a.constraint]??2)-(rank[b.constraint]??2)),used=Array(tail.length).fill(false),allowed=(index,constraint)=>{const relative=tail.length-1-index;if(relative<0||relative>2)return false;if(constraint==='last')return relative===0;if(constraint==='second')return relative===1;if(constraint==='third')return relative===2;if(constraint==='notlast')return relative===1||relative===2;return true},assign=i=>{if(i===ordered.length)return true;const rule=ordered[i];for(let j=0;j<tail.length;j++)if(!used[j]&&allowed(j,rule.constraint)&&anvilActionMatches(tail[j].id,rule.action)){used[j]=true;if(assign(i+1))return true;used[j]=false}return false};return assign(0)}
function anvilBfsWithRules(start,goal,rules,initialTail=[]){const seedTail=initialTail.slice(-3);if(start===goal&&anvilRulesSatisfied(seedTail,rules))return[];if(!rules.length)return anvilBfs(start,goal);const startKey=`${start}|${seedTail.map(a=>a.id).join(',')}`,queue=[{pos:start,tail:seedTail,key:startKey}],seen=new Set([startKey]),prev=new Map;for(let q=0;q<queue.length;q++){const state=queue[q];for(const action of ANVIL_ACTIONS){const next=state.pos+action.d;if(next<0||next>150)continue;const tail=[...state.tail,action].slice(-3),key=`${next}|${tail.map(a=>a.id).join(',')}`;if(seen.has(key))continue;seen.add(key);prev.set(key,[state.key,action]);if(next===goal&&anvilRulesSatisfied(tail,rules)){const path=[];for(let k=key;k!==startKey;){const[p,a]=prev.get(k);path.push(a);k=p}return path.reverse()}queue.push({pos:next,tail,key})}}return null}
function anvilActionFromDelta(delta){return ANVIL_ACTIONS.find(action=>action.d===delta)||null}
let liveAnvilState=null;
function calculateAnvil(live=false){const start=Math.round(+$(`#anvilStart`).value),target=Math.round(+$(`#anvilTarget`).value);if(!Number.isFinite(start)||!Number.isFinite(target)||start<0||start>150||target<0||target>150){if(!live)alert('Wartości kowadła muszą mieścić się od 0 do 150.');return}const fieldIds=[['#ruleLast','#ruleLastConstraint'],['#ruleSecond','#ruleSecondConstraint'],['#ruleThird','#ruleThirdConstraint']],rules=fieldIds.map(([actionId,constraintId])=>({action:$(actionId).value,constraint:$(constraintId).value||'any'})).filter(r=>r.action),rulesKey=rules.map(r=>`${r.action}@${r.constraint}`).join('|');if(rules.some(r=>r.constraint==='unknown')){setCaptureStatus('Nie udało się pewnie odczytać kresek pozycji reguł. Wybierz pozycję ręcznie w sekcji „Reguły końcowe”.','bad');return}let initialTail=[],trackedMove=false;if(live&&liveAnvilState&&liveAnvilState.target===target&&liveAnvilState.rulesKey===rulesKey){if(start===liveAnvilState.current)return;const observed=anvilActionFromDelta(start-liveAnvilState.current);if(observed){initialTail=[...liveAnvilState.tail,observed].slice(-3);trackedMove=true}}const path=anvilBfsWithRules(start,target,rules,initialTail),best=path?{path,finalCount:rules.length?Math.min(3,path.length):0}:null;if(live&&best)liveAnvilState={current:start,target,rulesKey,tail:initialTail};else if(!live)liveAnvilState=null;const results=$('#anvilResults'),next=$('#anvilNext');results.classList.remove('hidden');next.classList.remove('done');if(!best){liveAnvilState=null;next.innerHTML='<span>NASTĘPNY KROK</span><b>Brak rozwiązania</b><small>Sprawdź zasady</small>';$('#anvilSequence').innerHTML='';$('#anvilNote').textContent='Nie znaleziono ścieżki w zakresie kowadła 0–150.';return}const first=best.path[0];if(first)next.innerHTML=`<span>NASTĘPNY KROK</span>${actionIcon(first.id,true)}<b>${first.name}</b><small>${first.d>0?'+':''}${first.d} → ${start+first.d}</small>`;else{next.classList.add('done');next.innerHTML='<span>STATUS</span><b>Wartości wyrównane</b><small>Gotowe ✓</small>'}let pos=start;$('#anvilSequence').innerHTML=best.path.map((a,i)=>{pos+=a.d;const final=i>=best.path.length-best.finalCount;return `<div class="anvil-step ${final?'final':''}"><i>Krok ${i+1}${final?' · reguła':''}</i>${actionIcon(a.id)}<b>${a.name}</b><small>${a.d>0?'+':''}${a.d} → ${pos}</small></div>`}).join('');$('#anvilNote').textContent=`Start ${start} → cel ${target}. Pozostało ${best.path.length} operacji, w tym ${best.finalCount} końcowych.${live?trackedMove?' Ostatni ruch rozpoznany — pokazuję nową najkrótszą poprawną trasę.':' Pozycja zmieniła się o kilka ruchów — trasa została obliczona od nowa.':''}`;if(!live)results.scrollIntoView({behavior:'smooth',block:'start'})}
$('#anvilCalculate').onclick=()=>{$('#anvilTool').classList.remove('static-image-mode');calculateAnvil(false)};
setInterval(()=>{if(anvilCaptureStream&&anvilImageReady&&anvilMarkerState.accepted){refreshRulePreviews();calculateAnvil(true)}},100);
