const ALLOYS = {
  bronze:{name:'Brąz', metals:[['Miedź',88,92,'#d7783e'],['Cyna',8,12,'#b8b3a9']]},
  bismuth:{name:'Brąz bizmutowy', metals:[['Miedź',50,65,'#d7783e'],['Cynk',20,30,'#a9a7a0'],['Bizmut',10,20,'#d4a8bd']]},
  black:{name:'Czarny brąz', metals:[['Miedź',50,70,'#d7783e'],['Srebro',10,25,'#d7d9da'],['Złoto',10,25,'#e8b53f']]},
  brass:{name:'Mosiądz', metals:[['Miedź',88,92,'#d7783e'],['Cynk',8,12,'#a9a7a0']]},
  rose:{name:'Różowe złoto', metals:[['Miedź',15,30,'#d7783e'],['Złoto',70,85,'#e8b53f']]},
  sterling:{name:'Srebro sterlingowe', metals:[['Miedź',20,40,'#d7783e'],['Srebro',60,80,'#d7d9da']]},
  custom:{name:'＋ Dodaj własny stop…', metals:[['Miedź',50,50,'#d7783e'],['Cynk',50,50,'#d7d9da']]}
};
const $=s=>document.querySelector(s); let sizes=[144,36]; let lastText='';
const alloySelect=$('#alloySelect'); alloySelect.add(new Option(ALLOYS.custom.name,'custom'));Object.entries(ALLOYS).filter(([k])=>k!=='custom').forEach(([k,a])=>alloySelect.add(new Option(a.name,k))); alloySelect.value='black';

function render(){const a=ALLOYS[alloySelect.value],custom=alloySelect.value==='custom';$('#customActions').classList.toggle('hidden',!custom);$('#recipeInfo').innerHTML=a.metals.map(m=>`<span class="ratio-pill"><b>${m[0]}</b> ${custom?m[1]+'%':m[1]+'–'+m[2]+'%'}</span>`).join('');$('#materialRows').innerHTML=a.metals.map((m,i)=>custom?`<div class="material-row custom-metal" data-i="${i}"><div class="custom-editor"><label>Materiał<input class="custom-name" value="${m[0]}" maxlength="30" placeholder="np. Miedź"></label><label>Udział %<input class="custom-percent" type="number" min="0.01" max="100" step="0.01" value="${m[1]}"></label><button class="remove-metal" data-remove="${i}" title="Usuń materiał" ${a.metals.length<=2?'disabled':''}>×</button></div><div class="sizes">${sizes.map((s,j)=>`<div class="unit-input"><input aria-label="${m[0]} porcja ${j+1}" data-size="${j}" type="number" min="0" value="${s}"><span>mB</span></div>`).join('')}</div></div>`:`<div class="material-row" data-i="${i}"><div class="metal-name"><span class="dot" style="color:${m[3]};background:${m[3]}"></span>${m[0]}</div><div class="sizes">${sizes.map((s,j)=>`<div class="unit-input"><input aria-label="${m[0]} porcja ${j+1}" data-size="${j}" type="number" min="0" value="${s}"><span>mB</span></div>`).join('')}</div></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{a.metals.splice(+b.dataset.remove,1);render()})}

function syncCustom(){if(alloySelect.value!=='custom')return;document.querySelectorAll('.material-row').forEach((r,i)=>{const m=ALLOYS.custom.metals[i],percent=+r.querySelector('.custom-percent').value;m[0]=r.querySelector('.custom-name').value.trim()||`Materiał ${i+1}`;m[1]=percent;m[2]=percent})}

function solve(){syncCustom();const a=ALLOYS[alloySelect.value],cap=+$('#capacity').value||3024,target=$('#fillMax').checked?cap:Math.min(cap,+$('#target').value||cap);if(a.metals.some(m=>!Number.isFinite(m[1])||!Number.isFinite(m[2])||m[1]<=0||m[2]>100||m[1]>m[2]))return showError('Każdy udział procentowy musi być większy od 0 i nie może przekraczać 100%.');const minSum=a.metals.reduce((n,m)=>n+m[1],0),maxSum=a.metals.reduce((n,m)=>n+m[2],0);if(alloySelect.value==='custom'&&Math.abs(minSum-100)>0.0001)return showError(`Udziały własnego stopu muszą dawać dokładnie 100%. Teraz dają ${minSum.toFixed(2)}%.`);if(minSum>100||maxSum<100)return showError(`Z tych zakresów nie da się złożyć 100% stopu. Suma minimów: ${minSum}%, suma maksimów: ${maxSum}%.`);const rows=[...document.querySelectorAll('.material-row')];const units=rows.map(r=>[...r.querySelectorAll('.sizes input')].map(x=>+x.value).filter(x=>x>0));if(units.some(x=>!x.length))return showError('Każdy metal musi mieć przynajmniej jedną porcję większą od 0.');
  const tables=units.map(us=>{
    const dp=Array(target+1).fill(null);dp[0]={count:0,counts:Array(us.length).fill(0)};
    for(let mb=1;mb<=target;mb++)for(let j=0;j<us.length;j++){
      const u=us[j],prev=dp[mb-u];if(!prev)continue;
      if(!dp[mb]||prev.count+1<dp[mb].count){const counts=prev.counts.slice();counts[j]++;dp[mb]={count:prev.count+1,counts}}
    }
    const list=[];for(let mb=1;mb<=target;mb++)if(dp[mb])list.push({mb,count:dp[mb].count,parts:dp[mb].counts.map((n,j)=>({u:us[j],n})).filter(p=>p.n).sort((x,y)=>y.u-x.u)});
    return {list,byMb:new Map(list.map(o=>[o.mb,o]))};
  });
  const priority=$('#priority').value;let best=null;
  const better=c=>{const score=priority==='items'?[c.count,-c.sum]:priority==='primary'?[c.chosen.slice(1).reduce((n,x)=>n+x.mb,0),-c.sum]:[-c.sum,c.count];c.score=score;if(!best||score[0]<best.score[0]||(score[0]===best.score[0]&&score[1]<best.score[1]))best=c};
  const findAtTotal=total=>{
    const lists=tables.map((t,i)=>t.list.filter(o=>{const pct=o.mb/total*100;return pct>=a.metals[i][1]-1e-9&&pct<=a.metals[i][2]+1e-9}));
    if(lists.some(x=>!x.length))return false;let found=false;
    const walk=(idx,chosen,sum,count)=>{
      if(idx===tables.length-1){const last=tables[idx].byMb.get(total-sum);if(!last)return;const pct=last.mb/total*100;if(pct<a.metals[idx][1]-1e-9||pct>a.metals[idx][2]+1e-9)return;found=true;better({chosen:[...chosen,last],sum:total,count:count+last.count});return}
      const remaining=total-sum;for(const o of lists[idx]){if(o.mb>=remaining)break;walk(idx+1,[...chosen,o],sum+o.mb,count+o.count)}
    };walk(0,[],0,0);return found;
  };
  if(priority==='volume'){for(let total=target;total>0;total--)if(findAtTotal(total))break}else for(let total=1;total<=target;total++)findAtTotal(total);
  if(!best)return showError('Nie ma poprawnej kombinacji dla tych rozmiarów porcji i pojemności. Dodaj mniejszą porcję (np. 16 lub 36 mB).');show(best,a,cap)}

function show(b,a,cap){$('#results').classList.remove('hidden');$('#statusBadge').className='badge';$('#statusBadge').textContent='POPRAWNY STOP';$('#resultCards').innerHTML=b.chosen.map((x,i)=>{const pct=(x.mb/b.sum*100).toFixed(2);const detail=x.parts.map(p=>`${p.n} × ${p.u} mB`).join(' + ');return `<div class="result-card"><div><h3>${a.metals[i][0]}</h3><p>${detail} · ${x.mb} mB · ${pct}% (wymagane ${a.metals[i][1]}–${a.metals[i][2]}%)</p></div><div class="count">${x.count}<small>PORCJI</small></div></div>`}).join('');const fill=b.sum/cap*100;$('#fillBar').style.width=Math.min(100,fill)+'%';$('#totalMb').textContent=b.sum;$('#capacityOut').textContent=cap;$('#fillPercent').textContent=fill.toFixed(1)+'%';$('#itemCount').textContent=b.count;$('#ingotCount').textContent=Math.floor(b.sum/144);$('#remainder').textContent=(b.sum%144)+' mB';lastText=`${a.name} — ${b.sum} mB\n`+b.chosen.map((x,i)=>`${a.metals[i][0]}: ${x.parts.map(p=>`${p.n} × ${p.u} mB`).join(' + ')} = ${x.mb} mB (${(x.mb/b.sum*100).toFixed(2)}%)`).join('\n');$('#solverNote').textContent='Solver sprawdził całkowite kombinacje porcji mieszczące się w naczyniu i wybrał najlepszy wynik zgodnie z ustawionym priorytetem.';$('#results').scrollIntoView({behavior:'smooth',block:'start'})}
function showError(msg){$('#results').classList.remove('hidden');$('#statusBadge').className='badge bad';$('#statusBadge').textContent='BRAK KOMBINACJI';$('#resultCards').innerHTML=`<div class="result-card"><div><h3>Nie udało się ułożyć stopu</h3><p>${msg}</p></div></div>`;$('#solverNote').textContent='Zmień wielkości porcji lub pojemność i spróbuj ponownie.'}
alloySelect.onchange=render;$('#addSize').onclick=()=>{syncCustom();sizes.push(16);render()};$('#addMetal').onclick=()=>{syncCustom();if(ALLOYS.custom.metals.length>=4)return showError('Waza ma 4 sloty, dlatego własny stop może zawierać maksymalnie 4 materiały.');const i=ALLOYS.custom.metals.length+1;ALLOYS.custom.metals.push([`Materiał ${i}`,0,0,['#9cb76e','#72a9be','#b980cf','#df9b55'][i%4]]);render()};$('#calculateBtn').onclick=solve;$('#resetBtn').onclick=()=>{sizes=[144,36];alloySelect.value='black';ALLOYS.custom.metals=[['Miedź',50,50,'#d7783e'],['Cynk',50,50,'#d7d9da']];$('#capacity').value=$('#target').value=3024;$('#fillMax').checked=true;$('#target').disabled=true;$('#bloomCapacity').value=112;$('#bloomAvailable').value=0;$('#bloomMbItem').value=129;$('#bloomMbPer').value=100;$('#bloomCoalPer').value=2;$('#anvilStart').value=0;$('#anvilTarget').value=80;document.querySelectorAll('.anvil-rule').forEach(x=>x.value='');render();document.querySelectorAll('.results').forEach(x=>x.classList.add('hidden'))};$('#capacity').oninput=e=>{if($('#fillMax').checked)$('#target').value=e.target.value};$('#fillMax').onchange=e=>{if(e.target.checked)$('#target').value=$('#capacity').value;$('#target').disabled=e.target.checked};$('#target').disabled=true;$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(lastText);$('#copyBtn').textContent='Skopiowano ✓';setTimeout(()=>$('#copyBtn').textContent='Kopiuj rozpiskę',1400)};render();

const TOOL_COPY={alloy:['NARZĘDZIE HUTNICZE','Idealny stop.<br><em>Bez zgadywania.</em>','Dobierz całkowite porcje metalu, wypełnij naczynie i nie zmarnuj ani kropli.'],bloomery:['KALKULATOR BLOOMERY','Pełny wsad.<br><em>Bez marnowania.</em>','Oblicz pył, charcoal i liczbę bloomów z uwzględnieniem limitu konstrukcji.'],anvil:['SOLVER KOWADŁA','Perfectly forged.<br><em>Najkrótszą drogą.</em>','Wpisz cel i końcowe reguły, a solver znajdzie kolejność uderzeń.']};
document.querySelectorAll('.tool-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tool-tab,.tool-view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.tool}Tool`).classList.add('active');const c=TOOL_COPY[tab.dataset.tool];$('.hero .eyebrow').textContent=c[0];$('.hero h1').innerHTML=c[1];$('.hero .lede').textContent=c[2]});

function calculateBloomery(){const cap=Math.floor(+$(`#bloomCapacity`).value),available=Math.floor(+$(`#bloomAvailable`).value),mbItem=+$(`#bloomMbItem`).value,mbPer=+$(`#bloomMbPer`).value,coalPer=+$(`#bloomCoalPer`).value,whole=$('#bloomWhole').checked;if(![cap,mbItem,mbPer].every(x=>Number.isFinite(x)&&x>0)||!Number.isFinite(coalPer)||coalPer<0)return alert('Sprawdź wartości Bloomery.');let best=null,maxMetal=Math.min(cap,available>0?available:cap);for(let metal=1;metal<=maxMetal;metal++){const blooms=Math.floor(metal*mbItem/mbPer+1e-9),coal=Math.ceil(blooms*coalPer-1e-9),slots=metal+coal;if(!blooms||slots>cap)continue;const waste=metal*mbItem-blooms*mbPer;if(!best||blooms>best.blooms||(blooms===best.blooms&&((whole&&metal<best.metal)||(!whole&&metal>best.metal))))best={metal,blooms,coal,slots,waste,total:metal*mbItem}}if(!best){$('#bloomResults').classList.remove('hidden');$('#bloomCards').innerHTML='<div class="metric-card"><span>Brak wyniku</span><b>—</b><small>Zwiększ pojemność lub ilość materiału.</small></div>';return}$('#bloomResults').classList.remove('hidden');$('#bloomCards').innerHTML=`<div class="metric-card"><span>Pył / materiał</span><b>${best.metal}</b><small>${best.total} mB żelaza</small></div><div class="metric-card"><span>Charcoal</span><b>${best.coal}</b><small>${coalPer} na bloom</small></div><div class="metric-card"><span>Raw Iron Blooms</span><b>${best.blooms}</b><small>${best.blooms*mbPer} mB wykorzystane</small></div><div class="metric-card"><span>Zajęte miejsca</span><b>${best.slots}/${cap}</b><small>${cap-best.slots} wolnych</small></div>`;$('#bloomNote').textContent=`Reszta żelaza: ${best.waste.toFixed(0)} mB. Wsad: ${best.metal} × materiał po ${mbItem} mB + ${best.coal} × charcoal.`;$('#bloomResults').scrollIntoView({behavior:'smooth',block:'start'})}
$('#bloomCalculate').onclick=calculateBloomery;

const ANVIL_ACTIONS=[{id:'light',name:'Light Hit',d:-3},{id:'medium',name:'Medium Hit',d:-6},{id:'hard',name:'Hard Hit',d:-9},{id:'draw',name:'Draw',d:-15},{id:'punch',name:'Punch',d:2},{id:'bend',name:'Bend',d:7},{id:'upset',name:'Upset',d:13},{id:'shrink',name:'Shrink',d:16}],ANVIL_FAMILIES={hit:['light','medium','hard'],draw:['draw'],punch:['punch'],bend:['bend'],upset:['upset'],shrink:['shrink']};
const ruleOptions=[['','Brak'],['hit','Hit'],['draw','Draw'],['punch','Punch'],['bend','Bend'],['upset','Upset'],['shrink','Shrink']];document.querySelectorAll('.anvil-rule').forEach(s=>ruleOptions.forEach(([v,n])=>s.add(new Option(n,v))));
function anvilBfs(start,goal){if(start===goal)return[];const queue=[start],seen=Array(151).fill(false),prev=Array(151);seen[start]=true;for(let q=0;q<queue.length;q++){const pos=queue[q];for(const action of ANVIL_ACTIONS){const next=pos+action.d;if(next<0||next>150||seen[next])continue;seen[next]=true;prev[next]=[pos,action];if(next===goal){const path=[];for(let x=goal;x!==start;){const [p,a]=prev[x];path.push(a);x=p}return path.reverse()}queue.push(next)}}return null}
function calculateAnvil(){const start=Math.round(+$(`#anvilStart`).value),target=Math.round(+$(`#anvilTarget`).value);if(!Number.isFinite(start)||!Number.isFinite(target)||start<0||start>150||target<0||target>150)return alert('Wartości kowadła muszą mieścić się od 0 do 150.');const selected=[$('#ruleThird').value,$('#ruleSecond').value,$('#ruleLast').value].filter(Boolean),variants=[];const expand=(i,path)=>{if(i===selected.length)return variants.push(path);for(const id of ANVIL_FAMILIES[selected[i]])expand(i+1,[...path,ANVIL_ACTIONS.find(a=>a.id===id)])};expand(0,[]);if(!variants.length)variants.push([]);let best=null;for(const final of variants){const pre=target-final.reduce((n,a)=>n+a.d,0);if(pre<0||pre>150)continue;const setup=anvilBfs(start,pre);if(!setup)continue;let pos=pre,valid=true;for(const a of final){pos+=a.d;if(pos<0||pos>150){valid=false;break}}if(!valid||pos!==target)continue;const path=[...setup,...final];if(!best||path.length<best.path.length)best={path,finalCount:final.length}}$('#anvilResults').classList.remove('hidden');if(!best){$('#anvilSequence').innerHTML='<div class="metric-card"><span>Brak rozwiązania</span><b>—</b><small>Sprawdź cel i reguły końcowe.</small></div>';$('#anvilNote').textContent='Nie znaleziono ścieżki w zakresie kowadła 0–150.';return}let pos=start;$('#anvilSequence').innerHTML=best.path.map((a,i)=>{pos+=a.d;const final=i>=best.path.length-best.finalCount;return `<div class="anvil-step ${final?'final':''}"><i>Krok ${i+1}${final?' · reguła':''}</i><b>${a.name}</b><small>${a.d>0?'+':''}${a.d} → ${pos}</small></div>`}).join('');$('#anvilNote').textContent=`Start ${start} → cel ${target}. Łącznie ${best.path.length} operacji, w tym ${best.finalCount} wymaganych operacji końcowych.`;$('#anvilResults').scrollIntoView({behavior:'smooth',block:'start'})}
$('#anvilCalculate').onclick=calculateAnvil;
