/* TerraFirmaCraft 3.2.23 regional worldgen port (EUPL-1.2).
 * Generates the discrete 128-block region data used before quart-scale zooming.
 */
(()=>{
const I=globalThis.TFGMapCore._internals,{Xoroshiro128PlusPlus:Xoro,U64,clamp}=I,RADIUS=100,THRESHOLD=4.4;
const flag=(point,name)=>point[name]=true,fastRound=value=>Math.trunc(value+(value>=0?.5:-.5));
const floatBits=value=>{const b=new ArrayBuffer(4),v=new DataView(b);v.setFloat32(0,value);return v.getInt32(0)};
const floorMod=(value,n)=>{const b=BigInt(n),r=BigInt.asIntN(64,value)%b;return Number(r<0?r+b:r)};
const murmur=value=>{let x=U64(value);x=U64((x^(x>>33n))*0xff51afd7ed558ccdn);x=U64((x^(x>>33n))*0xc4ceb9fe1a85ec53n);return U64(x^(x>>33n))};

class AreaContext{
  constructor(seed){this.seed=murmur(seed);this.random=new Xoro(seed)}
  setSeed(x,z){this.random.setSeed(U64((U64(BigInt(x)*501125321n)^U64(BigInt(z)*1136930381n)^this.seed)*0x27d4eb2dn))}
  choose(...values){return values.length===2?(this.random.nextBoolean()?values[0]:values[1]):values[this.random.nextInt(values.length)]}
}
const cached=source=>{const cache=new Map;return(x,z)=>{const key=`${x},${z}`;if(cache.has(key))return cache.get(key);const value=source(x,z);if(cache.size>160000)cache.clear();cache.set(key,value);return value}};
function uniform(seed){const context=new AreaContext(seed);return cached((x,z)=>{context.setSeed(x,z);return context.random.nextInt()})}
function zoom(prev,seed){const context=new AreaContext(seed);return cached((x,z)=>{context.setSeed(x,z);const px=x>>1,pz=z>>1,ox=x&1,oz=z&1,nw=prev(px,pz);if(!ox&&!oz)return nw;if(!ox)return context.choose(nw,prev(px,pz+1));if(!oz)return context.choose(nw,prev(px+1,pz));const sw=prev(px,pz+1),ne=prev(px+1,pz),se=prev(px+1,pz+1);if(nw===sw)return nw===ne||ne!==se?nw:context.choose(nw,ne);if(nw===ne)return sw!==se?nw:context.choose(nw,sw);if(nw===se)return sw!==ne?nw:context.choose(nw,sw);if(sw===ne||sw===se)return sw;if(ne===se)return ne;return context.choose(nw,sw,ne,se)})}
function smooth(prev,seed){const context=new AreaContext(seed);return cached((x,z)=>{context.setSeed(x,z);const north=prev(x,z-1),east=prev(x+1,z),south=prev(x,z+1),west=prev(x-1,z),center=prev(x,z),equalX=west===east,equalZ=north===south;if(equalX===equalZ)return equalX?context.choose(east,north):center;return equalX?east:north})}
function uniformArea(random,levels){let area=uniform(random.nextLong());for(let i=0;i<levels;i++){area=zoom(area,random.nextLong());area=smooth(area,random.nextLong())}return area}

class JavaRandom{
  constructor(seed){this.mask=(1n<<48n)-1n;this.seed=(BigInt.asUintN(64,seed)^0x5deece66dn)&this.mask}
  next(bits){this.seed=(this.seed*0x5deece66dn+0xbn)&this.mask;return Number(this.seed>>BigInt(48-bits))}
  nextInt(){return this.next(32)|0}
  nextLong(){return U64((BigInt(this.nextInt())<<32n)+BigInt(this.nextInt()))}
}
const adjacent=(prev,seed,transform)=>{const context=new AreaContext(seed);return cached((x,z)=>{context.setSeed(x,z);return transform(context,prev(x,z-1),prev(x+1,z),prev(x,z+1),prev(x-1,z),prev(x,z))})};
const isOcean=biome=>['Ocean','Ocean Reef','Deep Ocean','Deep Ocean Trench'].includes(biome);
const isMountains=biome=>['Mountains','Oceanic Mountains','Old Mountains','Volcanic Mountains','Volcanic Oceanic Mountains'].includes(biome);
const isLow=biome=>['Plains','Hills','Low Canyons','Lowlands','Salt Marsh'].includes(biome);
const hasShore=biome=>!['Lowlands','Salt Marsh','Low Canyons','Canyons','Oceanic Mountains','Volcanic Oceanic Mountains'].includes(biome);
const shoreFor=biome=>biome==='Mountains'?'Oceanic Mountains':biome==='Volcanic Mountains'?'Volcanic Oceanic Mountains':'Shore';
const hasLake=biome=>!isOcean(biome)&&biome!=='Badlands';
const lakeFor=biome=>({'Mountains':'Mountain Lake','Volcanic Mountains':'Volcanic Mountain Lake','Old Mountains':'Old Mountain Lake','Oceanic Mountains':'Oceanic Mountain Lake','Volcanic Oceanic Mountains':'Volcanic Oceanic Mountain Lake','Plateau':'Plateau Lake'}[biome]||'Lake');
function createBiomeLayer(generator,seed){
  const random=new JavaRandom(seed);random.nextLong();
  let layer=cached((x,z)=>generator.sampleGrid(x,z).biome);
  layer=adjacent(layer,random.nextLong(),(context,n,e,s,w,c)=>{const any=predicate=>predicate(n)||predicate(e)||predicate(s)||predicate(w);if(isLow(c)){if(any(isOcean)&&any(isMountains))return'Oceanic Mountains';if(any(isOcean)&&any(v=>v==='Lowlands'))return'Salt Marsh'}if(['Plateau','Badlands','Inverted Badlands'].includes(c)){if(any(v=>v==='Low Canyons'||v==='Lowlands'))return'Hills';if(any(v=>v==='Plains'||v==='Hills'))return'Rolling Hills'}else if(isMountains(c)){if(any(isLow))return'Rolling Hills'}else if(c==='Lowlands'||c==='Low Canyons'){if(any(v=>['Plateau','Badlands','Inverted Badlands'].includes(v)))return'Hills';if(any(isMountains))return'Rolling Hills'}else if(c==='Plains'||c==='Hills'){if(any(v=>['Plateau','Badlands','Inverted Badlands'].includes(v)))return'Hills';if(any(isMountains))return'Rolling Hills'}else if(c==='Deep Ocean Trench'&&any(v=>!isOcean(v)))return'Ocean';return c});
  layer=zoom(layer,random.nextLong());
  layer=adjacent(layer,random.nextLong(),(context,n,e,s,w,c)=>!isOcean(c)&&hasShore(c)&&(isOcean(n)||isOcean(e)||isOcean(s)||isOcean(w))?shoreFor(c):c);
  layer=adjacent(layer,random.nextLong(),(context,n,e,s,w,c)=>c==='Ocean'&&[n,e,s,w].includes('Shore')&&![n,e,s,w].some(isMountains)?'Tidal Flats':c);
  for(let i=0;i<4;i++)layer=zoom(layer,random.nextLong());
  return smooth(layer,random.nextLong());
}

class Region{
  constructor(cell){const cx=fastRound(cell.x),cz=fastRound(cell.y);this.cell=cell;this.minX=cx-RADIUS;this.minZ=cz-RADIUS;this.maxX=cx+RADIUS;this.maxZ=cz+RADIUS;this.sizeX=201;this.sizeZ=201;this.data=new Array(201*201);this.rivers=[]}
  in(x,z){return x>=this.minX&&x<=this.maxX&&z>=this.minZ&&z<=this.maxZ}
  index(x,z){return(x-this.minX)+this.sizeX*(z-this.minZ)}
  at(x,z){return this.in(x,z)?this.data[this.index(x,z)]:null}
  offset(index,dx,dz){const x=index%this.sizeX+dx,z=Math.floor(index/this.sizeX)+dz;return x>=0&&x<this.sizeX&&z>=0&&z<this.sizeZ?x+this.sizeX*z:-1}
  shrink(minX,minZ,maxX,maxZ){const sx=1+maxX-minX,sz=1+maxZ-minZ,next=new Array(sx*sz),ox=minX-this.minX,oz=minZ-this.minZ;for(let z=0;z<sz;z++)for(let x=0;x<sx;x++)next[x+sx*z]=this.data[(ox+x)+this.sizeX*(oz+z)];this.minX=minX;this.minZ=minZ;this.maxX=maxX;this.maxZ=maxZ;this.sizeX=sx;this.sizeZ=sz;this.data=next}
}
const point=()=>({land:false,island:false,shore:false,river:false,lake:false,mountain:false,coastalMountain:false,distanceToOcean:0,distanceToEdge:0,baseOceanDepth:0,baseLandHeight:0,altitude:0,temperature:0,rainfall:0,biome:'Ocean',rock:'Unknown'});
const neighbors=(region,index,callback)=>{for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){const next=region.offset(index,dx,dz);if(next!==-1)callback(next,dx,dz)}};

const BIOMES={
  mountain:['Mountains','Mountains','Mountains','Old Mountains','Old Mountains','Plateau','Highlands'],
  coastal:['Volcanic Mountains','Volcanic Oceanic Mountains','Volcanic Oceanic Mountains','Oceanic Mountains','Oceanic Mountains','Rolling Hills'],
  altitude:[['Plains','Plains','Hills','Hills','Rolling Hills','Low Canyons','Lowlands','Lowlands'],['Plains','Hills','Rolling Hills','Highlands','Inverted Badlands','Badlands','Plateau','Canyons','Low Canyons'],['Highlands','Highlands','Highlands','Rolling Hills','Badlands','Plateau','Plateau','Old Mountains','Old Mountains']],
  island:['Plains','Hills','Rolling Hills','Volcanic Oceanic Mountains','Volcanic Oceanic Mountains'],
  midOcean:['Deep Ocean','Ocean','Ocean','Ocean Reef','Ocean Reef','Ocean Reef']
};
const ROCK_COLORS={andesite:[96,96,96],basalt:[29,32,33],chalk:[199,199,193],chert:[122,78,70],claystone:[141,102,68],conglomerate:[111,113,101],dacite:[122,123,123],diorite:[142,142,142],dolomite:[60,70,89],gabbro:[93,85,68],gneiss:[115,109,96],granite:[85,70,74],limestone:[136,127,107],marble:[227,235,235],phyllite:[148,157,169],quartzite:[140,129,128],rhyolite:[115,98,103],schist:[77,84,65],shale:[70,67,70],slate:[125,116,103]};
const ROCK_ROOTS={
  ocean:['rhyolite','andesite','dacite','basalt'],
  volcanic:['rhyolite','andesite','dacite','basalt','rhyolite','andesite','dacite','basalt'],
  land:['rhyolite','andesite','dacite','basalt','shale','claystone','conglomerate','limestone','dolomite','chalk','chert'],
  uplift:['shale','claystone','conglomerate','limestone','dolomite','chalk','chert','slate','marble','quartzite','diorite','granite','gabbro']
};

const lineDistanceSq=(vx,vy,wx,wy,px,py)=>{const l2=(vx-wx)**2+(vy-wy)**2,t=l2===0?0:clamp(((px-vx)*(wx-vx)+(py-vy)*(wy-vy))/l2,0,1),x=vx+t*(wx-vx),y=vy+t*(wy-vy);return(x-px)**2+(y-py)**2};
const linesIntersect=(p1,q1,p2,q2)=>{const orientation=(p,q,r)=>{const v=(q.y-p.y)*(r.x-q.x)-(q.x-p.x)*(r.y-q.y);return v===0?0:v>0?1:2},collinear=(p,q,r)=>q.x<=Math.max(p.x,r.x)&&q.x>=Math.min(p.x,r.x)&&q.y<=Math.max(p.y,r.y)&&q.y>=Math.min(p.y,r.y),o1=orientation(p1,q1,p2),o2=orientation(p1,q1,q2),o3=orientation(p2,q2,p1),o4=orientation(p2,q2,q1);return o1!==o2&&o3!==o4||o1===0&&collinear(p1,p2,q1)||o2===0&&collinear(p1,q2,q1)||o3===0&&collinear(p2,p1,q2)||o4===0&&collinear(p2,q1,q2)};
const mcSin=value=>Math.fround(Math.sin((Math.trunc(Math.fround(value)*10430.378)&65535)*Math.PI*2/65536));
const mcCos=value=>Math.fround(Math.sin(((Math.trunc(Math.fround(value)*10430.378)+16384)&65535)*Math.PI*2/65536));
class RiverBuilder{
  constructor(random,x,y,angle,length,depth,feather){this.random=random;this.edges=[];this.queue=[];this.branch=[];this.root={x,y,angle,length,distance:0};this.depth=depth;this.featherSq=feather*feather}
  computeNext(prev,length,distance){const angle=distance===0?prev.angle:prev.angle+(this.random.nextDouble()*.5+.2)*(this.random.nextBoolean()?1:-1),nextLength=length*(this.random.nextDouble()*.08+.92);return{x:prev.x+mcCos(Math.fround(angle))*nextLength,y:prev.y+mcSin(Math.fround(angle))*nextLength,angle,length:nextLength,distance:distance+1}}
  intersects(edge){for(const e of this.edges)if(e.source!==edge.drain&&e.drain!==edge.drain&&(lineDistanceSq(e.source.x,e.source.y,e.drain.x,e.drain.y,edge.source.x,edge.source.y)<this.featherSq||linesIntersect(e.source,e.drain,edge.source,edge.drain)))return true;return false}
  prune(){if(this.edges.length<6){this.edges.length=0;this.queue.length=0}}
  initial(context){let prev=this.root,length=this.depth+this.random.nextInt(1+Math.trunc(this.depth*.3));for(let i=0;i<length;i++){const next=this.computeNext(prev,prev.length,prev.distance),edge={source:next,drain:prev};if(context.intersectAny(edge)){this.prune();return true}this.edges.push(edge);prev=next;if(prev.distance<this.depth&&prev.distance>=2)this.queue.push(edge)}return false}
  buildBranch(context){if(!this.queue.length){this.prune();return true}const prevEdge=this.queue.shift();let prev=prevEdge.drain,prevDist=prev.distance+this.random.nextInt(3),next=this.computeNext(prev,prev.length,prevDist),delta=Math.abs(prevEdge.source.angle-next.angle);if(delta<.4||2*Math.PI-delta<.4)return false;this.branch.length=0;let edge={source:next,drain:prev};if(context.intersectAny(edge))return false;this.branch.push(edge);prev=next;for(let i=0;i<this.depth-prev.distance+this.random.nextInt(1+Math.trunc(this.depth*.3));i++){next=this.computeNext(prev,prev.length,prevDist);edge={source:next,drain:prev};if(context.intersectAny(edge))break;this.branch.push(edge);prev=next;prevDist=next.distance;if(prevDist<this.depth&&prevDist>=2)this.queue.push(edge)}this.edges.push(...this.branch);return false}
}
class RiverNetwork{
  constructor(region){this.region=region;this.builders=[]}
  add(builder){this.builders.push(builder)}
  legal(prev,vertex){const a=this.vertexPoint(prev),b=this.vertexPoint(vertex);return!!(a&&b&&b.land&&b.distanceToOcean>=a.distanceToOcean&&b.distanceToOcean>=Math.min(3,prev.distance/2))}
  vertexPoint(vertex){return this.region.at(Math.round(vertex.x),Math.round(vertex.y))}
  intersectAny(edge){if(!this.legal(edge.drain,edge.source))return true;return this.builders.some(builder=>builder.intersects(edge))}
  build(){const working=[];for(const builder of this.builders)if(builder.initial(this))working.push(builder);while(working.length){working.sort((a,b)=>(b.edges.length+10*b.queue.length)-(a.edges.length+10*a.queue.length));const builder=working.shift();if(!builder.buildBranch(this))working.push(builder)}return this.builders.flatMap(builder=>builder.edges)}
}
function midpointFractal(random,edge){let segments=[edge.source.x,edge.source.y,edge.drain.x,edge.drain.y];for(let pass=0;pass<4;pass++){const split=new Array(segments.length*2-2);split[0]=segments[0];split[1]=segments[1];let out=2;for(let i=0;i<segments.length-2;i+=2){const sx=segments[i],sy=segments[i+1],dx=segments[i+2],dy=segments[i+3],norm=Math.max(Math.abs(sx-dx),Math.abs(sy-dy)),jitter=()=>{const v=2*random.nextDouble()-1;return.15*v+(v<0?-.05:.05)};split[out]=jitter()*norm+(sx+dx)*.5;split[out+1]=jitter()*norm+(sy+dy)*.5;split[out+2]=dx;split[out+3]=dy;out+=4}segments=split}return segments}
const fractalDistanceSq=(segments,x,z)=>{let min=Number.MAX_VALUE;for(let i=0;i<segments.length-2;i+=2)min=Math.min(min,lineDistanceSq(segments[i],segments[i+1],segments[i+2],segments[i+3],x,z));return min};

class Generator{
  constructor({levelSeed,regionSeed,cells,continent,rawClimate}){this.levelSeed=levelSeed;this.regionSeed=regionSeed;this.cells=cells;this.continent=continent;this.rawClimate=rawClimate;this.cache=new Map;this.partitionCache=new Map;const sequence=new Xoro(levelSeed);for(let i=0;i<5;i++)sequence.nextLong();this.biomeArea=uniformArea(sequence,2);this.rockArea=uniformArea(sequence,3);this.chunkDataSeed=sequence.nextLong();this.biomeLayer=createBiomeLayer(this,sequence.nextLong())}
  sampleGrid(gx,gz){const cell=this.cells.cell(gx,gz),region=this.getRegion(cell);return region.at(gx,gz)}
  sample(blockX,blockZ){const exactX=blockX/128,exactZ=blockZ/128,gx=Math.floor(exactX),gz=Math.floor(exactZ),dx=exactX-gx,dz=exactZ-gz,p00=this.sampleGrid(gx,gz),p10=this.sampleGrid(gx+1,gz),p01=this.sampleGrid(gx,gz+1),p11=this.sampleGrid(gx+1,gz+1),bilerp=field=>(p00[field]*(1-dx)+p10[field]*dx)*(1-dz)+(p01[field]*(1-dx)+p11[field]*dx)*dz,temperature=bilerp('temperature'),rainfall=bilerp('rainfall'),biome=this.biomeLayer(Math.floor(blockX/4),Math.floor(blockZ/4));return{...p00,temperature,rainfall,biome,kaolinEligible:['Plateau','Highlands','Old Mountains'].includes(biome)&&temperature>=18&&rainfall>=300}}
  getRegion(cell){const key=`${cell.cx},${cell.cy}`;let region=this.cache.get(key);if(!region){region=this.createRegion(cell);if(this.cache.size>128)this.cache.clear();this.cache.set(key,region)}return region}
  createRegion(cell){
    const region=new Region(cell),bits=floatBits(cell.noise),random=new Xoro(U64(this.regionSeed^U64(BigInt(bits)*7189234123n)));let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity;
    for(let z=region.minZ;z<=region.maxZ;z++)for(let x=region.minX;x<=region.maxX;x++){const owner=this.cells.cell(x,z);if(owner.x===cell.x&&owner.y===cell.y){const p=point();if(this.continent(x,z)>THRESHOLD)p.land=true;region.data[region.index(x,z)]=p;minX=Math.min(minX,x);minZ=Math.min(minZ,z);maxX=Math.max(maxX,x);maxZ=Math.max(maxZ,z)}}
    region.shrink(minX,minZ,maxX,maxZ);this.distanceToEdge(region);this.fillSmallOceans(region);this.addIslands(region,random);this.distanceToOcean(region);this.baseHeight(region,random);this.addMountains(region,random);this.altitude(region,random);this.climate(region);this.chooseBiomes(region,random);this.chooseRocks(region);this.addRivers(region,random);return region;
  }
  distanceToEdge(region){const explored=new Uint8Array(region.data.length),queue=[];let head=0;for(let z=0;z<region.sizeZ;z++)for(let x=0;x<region.sizeX;x++){const i=x+region.sizeX*z,p=region.data[i];if(!p||x===0||z===0||x===region.sizeX-1||z===region.sizeZ-1){explored[i]=1;queue.push(i);if(p)p.distanceToEdge=-1}}while(head<queue.length){const last=queue[head++],lp=region.data[last],distance=lp?lp.distanceToEdge+1:0;neighbors(region,last,next=>{const p=region.data[next];if(p&&p.distanceToEdge===0&&!explored[next]){p.distanceToEdge=distance;explored[next]=1;queue.push(next)}else explored[next]=1})}}
  fillSmallOceans(region){const explored=new Uint8Array(region.data.length);for(let i=0;i<region.data.length;i++){const start=region.data[i];if(explored[i]||!start||start.land)continue;const values=[i],queue=[i];let head=0,unbounded=false;explored[i]=1;while(head<queue.length){const last=queue[head++];for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++){const next=region.offset(last,dx,dz);if(next===-1||!region.data[next]){unbounded=true;continue}if(region.data[next].land||explored[next])continue;explored[next]=1;queue.push(next);values.push(next)}}if(values.length<180&&!unbounded)for(const n of values)region.data[n].land=true}}
  addIslands(region,random){for(let attempt=0,placed=0;attempt<130&&placed<15;attempt++){let x=region.minX+random.nextInt(region.sizeX),z=region.minZ+random.nextInt(region.sizeZ),p=region.at(x,z);if(p&&!p.land&&!p.shore&&p.distanceToEdge>2){for(let n=0;n<12;n++){p.land=p.island=true;x+=random.nextInt(4)-random.nextInt(4);z+=random.nextInt(4)-random.nextInt(4);p=region.at(x,z);if(!p||(p.land&&!p.island)||p.distanceToEdge<=2)break}placed++}}}
  distanceToOcean(region){const explored=new Uint8Array(region.data.length),queue=[];let head=0;for(let i=0;i<region.data.length;i++){const p=region.data[i];if(p&&!p.land){p.distanceToOcean=-1;queue.push(i);explored[i]=1}}while(head<queue.length){const last=queue[head++],lp=region.data[last],distance=lp.distanceToOcean+1;neighbors(region,last,next=>{const p=region.data[next];if(p&&p.land&&p.distanceToOcean===0){if(!lp.land&&!p.island)lp.shore=true;if(!explored[next]){p.distanceToOcean=distance;queue.push(next)}}explored[next]=1})}}
  baseHeight(region,random){const explored=new Uint8Array(region.data.length),queue=[],islands=[];let head=0;for(let i=0;i<region.data.length;i++){const p=region.data[i];if(p&&p.land){p.baseLandHeight=p.distanceToOcean;if(p.baseLandHeight>p.distanceToEdge)p.baseLandHeight=Math.trunc(.3*p.baseLandHeight+.7*p.distanceToEdge);explored[i]=1;if(p.island){p.baseOceanDepth=3;islands.push(i)}else queue.push(i)}}while(head<queue.length){const last=queue[head++],lp=region.data[last],depth=lp.baseOceanDepth+1;if(depth===3&&islands.length){queue.push(...islands);islands.length=0}neighbors(region,last,next=>{const p=region.data[next];if(p&&!p.land&&p.baseOceanDepth===0&&!explored[next]){if(random.nextInt(15)===0){p.baseOceanDepth=lp.baseOceanDepth;queue.splice(head,0,next)}else{p.baseOceanDepth=depth;queue.push(next)}}explored[next]=1})}}
  addMountains(region,random){for(let attempt=0,placed=0;attempt<40&&placed<3;attempt++){const x=region.minX+random.nextInt(region.sizeX),z=region.minZ+random.nextInt(region.sizeZ),origin=region.at(x,z);if(!origin||!origin.land||!(origin.baseLandHeight<=1||(origin.baseLandHeight>=4&&origin.baseLandHeight<=11)))continue;const range=this.placeRange(region,random,region.index(x,z));if(range.size>45){for(const i of range){region.data[i].mountain=true;if(origin.baseLandHeight<=2)region.data[i].coastalMountain=true}placed++}}}
  placeRange(region,random,origin){const explored=new Uint8Array(region.data.length),queue=[origin],range=new Set([origin]),base=Math.max(1,region.data[origin].baseLandHeight),max=70+random.nextInt(40);explored[origin]=1;let head=0;while(head<queue.length&&range.size<=max){const last=queue[head++],lp=region.data[last];neighbors(region,last,next=>{const p=region.data[next];if(p&&p.land&&p.baseLandHeight>=base-1&&p.baseLandHeight<=base+1&&(p.baseLandHeight>2||p.distanceToOcean<3)&&!explored[next]){if(lp.baseLandHeight!==p.baseLandHeight)queue.push(next);else queue.splice(head,0,next);range.add(next)}explored[next]=1})}return range}
  altitude(region,random){const explored=new Uint8Array(region.data.length),queue=[];let head=0;for(let i=0;i<region.data.length;i++){const p=region.data[i];if(p&&p.land&&p.mountain){p.altitude=12;queue.push(i);explored[i]=1}}while(head<queue.length){const last=queue[head++],lp=region.data[last],nextAltitude=lp.altitude-1;if(nextAltitude<0)continue;neighbors(region,last,next=>{const p=region.data[next];if(p&&p.land&&p.altitude===0&&!explored[next]){if(random.nextInt(13)===0&&lp.altitude!==12){p.altitude=lp.altitude;queue.splice(head,0,next)}else{p.altitude=nextAltitude;queue.push(next)}}explored[next]=1})}for(const p of region.data)if(p&&p.land&&Math.floor(p.altitude/4)===0&&p.baseLandHeight>=4){p.altitude=4;if(p.baseLandHeight>=11)p.altitude=8}}
  climate(region){for(let z=region.minZ;z<=region.maxZ;z++)for(let x=region.minX;x<=region.maxX;x++){const p=region.at(x,z);if(!p)continue;const raw=this.rawClimate(x,z);p.temperature=raw.temperature;p.rainfall=raw.rainfall;let bias=0;if(p.land)bias=Math.min(clamp((p.distanceToEdge-2)/4,0,1),clamp((p.distanceToOcean-2)/4,0,1));const targetT=5+(p.temperature-5)*bias,targetR=Math.min(p.rainfall+350,500)+(p.rainfall-Math.min(p.rainfall+350,500))*bias;p.temperature=p.temperature+(targetT-p.temperature)*.23;p.rainfall=p.rainfall+(targetR-p.rainfall)*.23}}
  chooseBiomes(region,random){const rngSeed=random.nextLong(),climateSeed=random.nextLong();for(let z=region.minZ;z<=region.maxZ;z++)for(let x=region.minX;x<=region.maxX;x++){const p=region.at(x,z);if(!p)continue;const area=this.biomeArea(x,z),pick=choices=>choices[floorMod(rngSeed^BigInt(area),choices.length)];if(p.island)p.biome=pick(BIOMES.island);else if(p.mountain)p.biome=pick(p.coastalMountain?BIOMES.coastal:BIOMES.mountain);else if(p.land)p.biome=pick(BIOMES.altitude[Math.min(2,Math.floor(p.altitude/4))]);else if(p.baseOceanDepth<3)p.biome='Ocean';else if(p.baseOceanDepth>9)p.biome='Deep Ocean Trench';else if(p.baseOceanDepth>=5||p.distanceToEdge<2)p.biome='Deep Ocean';else p.biome=pick(BIOMES.midOcean);const minRain=90+floorMod(BigInt(area)^climateSeed,40),maxRain=420+floorMod(BigInt(area)^climateSeed,40);if(p.rainfall<minRain){if(p.biome==='Lowlands')p.biome='Plains';else if(p.biome==='Low Canyons')p.biome='Canyons'}if(p.rainfall>maxRain){if(p.biome==='Badlands')p.biome='Highlands';else if(p.biome==='Inverted Badlands')p.biome='Rolling Hills'}}}
  chooseRocks(region){for(let i=0;i<region.data.length;i++){const p=region.data[i];if(!p)continue;let type=p.land?'land':'ocean',min=1e9;for(let dx=-2;dx<=2;dx++)for(let dz=0;dz<=2;dz++){const next=region.offset(i,dx,dz),dist=Math.abs(dx)+Math.abs(dz);if(next!==-1&&dist<min){const q=region.data[next];if(q?.island&&dist<4){type='volcanic';min=dist}else if((q?.mountain||q?.coastalMountain)&&dist<3){type='uplift';min=dist}}}const area=this.rockArea(region.minX+i%region.sizeX,region.minZ+Math.floor(i/region.sizeX)),root=ROCK_ROOTS[type],random=new Xoro(BigInt(area));p.rock=root[random.nextInt(root.length)]}}
  addRivers(region,random){
    const network=new RiverNetwork(region);
    for(let dx=0;dx<region.sizeX;dx++)for(let dz=0;dz<region.sizeZ;dz++){const index=dx+region.sizeX*dz,p=region.data[index];if(!p?.shore)continue;let best=Number.MIN_VALUE,count=0,angle=NaN;for(let dirX=-1;dirX<=1;dirX++)for(let dirZ=-1;dirZ<=1;dirZ++){if(!dirX&&!dirZ)continue;const next=region.offset(index,4*dirX,4*dirZ);if(next===-1||!region.data[next]?.land)continue;const metric=region.data[next].distanceToOcean-Math.abs(dirX)-Math.abs(dirZ);if(metric>best||(metric===best&&random.nextInt(1+count)===0)){if(metric>best){best=metric;count=0}count++;angle=Math.atan2(dirZ,dirX)}}if(!Number.isNaN(angle)){angle+=random.nextFloat()*.2-.1;network.add(new RiverBuilder(new Xoro(random.nextLong()),region.minX+dx+.5,region.minZ+dz+.5,angle,2.7,17,.8));p.river=true}}
    const raw=network.build(),edges=raw.map(edge=>{const segments=midpointFractal(random,edge),xs=[],zs=[];for(let i=0;i<segments.length;i+=2){xs.push(segments[i]);zs.push(segments[i+1])}return{...edge,segments,width:0,sourceEdge:false,drainEdge:null,minX:Math.min(...xs)-.5,maxX:Math.max(...xs)+.5,minZ:Math.min(...zs)-.5,maxZ:Math.max(...zs)+.5}}),bySource=new Map(edges.map(edge=>[edge.source,edge]));
    for(const edge of edges){edge.drainEdge=bySource.get(edge.drain)||null;if(edge.drainEdge)edge.drainEdge.sourceEdge=true}
    for(const source of edges)if(!source.sourceEdge){let edge=source,width=8;while(edge){edge.width=Math.max(edge.width,width);edge=edge.drainEdge;width=Math.min(width+2,24)}}
    for(const edge of edges)if(!edge.sourceEdge&&random.nextInt(3)===0)for(const[ox,oz]of[[1,1],[-1,1],[1,-1],[-1,-1]]){const gx=Math.trunc(edge.source.x+.3*ox),gz=Math.trunc(edge.source.y+.3*oz),p=region.at(gx,gz);if(p?.land&&p.distanceToOcean>=2&&p.distanceToEdge>=2&&hasLake(p.biome)){p.biome=lakeFor(p.biome);p.lake=true;p.rainfall+=.09*(500-p.rainfall)}}
    region.rivers=edges;
  }
  partitionRivers(gx,gz){const cellX=Math.floor(gx/96),cellZ=Math.floor(gz/96),key=`${cellX},${cellZ}`;if(this.partitionCache.has(key))return this.partitionCache.get(key);const regions=new Set,edges=[];for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)regions.add(this.getRegion(this.cells.cell((cellX+dx)*96,(cellZ+dz)*96)));for(const region of regions)edges.push(...region.rivers);if(this.partitionCache.size>32)this.partitionCache.clear();this.partitionCache.set(key,edges);return edges}
  sampleRiver(blockX,blockZ){const gx=blockX/128,gz=blockZ/128;let normalized=Number.MAX_VALUE;for(const edge of this.partitionRivers(gx,gz)){if(gx<edge.minX||gx>edge.maxX||gz<edge.minZ||gz>edge.maxZ)continue;const dist=fractalDistanceSq(edge.segments,gx,gz)*16384,norm=dist/Math.max(64,edge.width*edge.width);if(norm<normalized)normalized=norm}return{hit:normalized<1.1,normalized}}
  rasterRivers(centerX,centerZ,span,width,height){const verticalSpan=span*height/width,minX=centerX-span/2,maxX=centerX+span/2,minZ=centerZ-verticalSpan/2,maxZ=centerZ+verticalSpan/2,mask=new Uint8Array(width*height),edges=new Set,gx0=Math.floor(minX/128/96)-1,gx1=Math.floor(maxX/128/96)+1,gz0=Math.floor(minZ/128/96)-1,gz1=Math.floor(maxZ/128/96)+1,minVisibleWidth=span>=64000?22:span>=32000?18:span>=16000?14:span>=8000?10:8;for(let cx=gx0;cx<=gx1;cx++)for(let cz=gz0;cz<=gz1;cz++)for(const edge of this.partitionRivers(cx*96,cz*96))edges.add(edge);const mark=(x,y,r)=>{const x0=Math.max(0,Math.floor(x-r)),x1=Math.min(width-1,Math.ceil(x+r)),y0=Math.max(0,Math.floor(y-r)),y1=Math.min(height-1,Math.ceil(y+r));for(let py=y0;py<=y1;py++)for(let px=x0;px<=x1;px++)if((px-x)**2+(py-y)**2<=(r+.65)**2)mask[py*width+px]=255};for(const edge of edges){if(edge.width<minVisibleWidth)continue;const radius=Math.max(.55,edge.width/span*width),s=edge.segments;for(let i=0;i<s.length-2;i+=2){const x0=(s[i]*128-minX)/span*(width-1),y0=(s[i+1]*128-minZ)/verticalSpan*(height-1),x1=(s[i+2]*128-minX)/span*(width-1),y1=(s[i+3]*128-minZ)/verticalSpan*(height-1);if(Math.max(x0,x1)<-2||Math.min(x0,x1)>width+2||Math.max(y0,y1)<-2||Math.min(y0,y1)>height+2)continue;const steps=Math.max(1,Math.ceil(Math.max(Math.abs(x1-x0),Math.abs(y1-y0))));for(let n=0;n<=steps;n++){const t=n/steps;mark(x0+(x1-x0)*t,y0+(y1-y0)*t,radius)}}}return mask}
}

globalThis.TFGRegionV20={create(options){return new Generator(options)},rockColors:ROCK_COLORS};
})();
